### ISSUE TITLE
3.0.0 removes symbols without bumping soversion

### ISSUE THREAD

**Issue by darix** [harfbuzz/harfbuzz#3229] opened 2021-09-24 11:09 UTC
Running an app compiled with 2.9.1 against 3.0.0  fails with

```
/usr/lib64/chromium/chromium: symbol lookup error:
/usr/lib64/chromium/chromium: undefined symbol: hb_subset_input_set_retain_gids
```

Wouldnt this need a bump in the so version if you change the library in a backwards incompatible way?

**Comment by khaledhosny** [comment] 2021-09-24 11:24
Duplicate of #3227

**Comment by khaledhosny** [comment] 2021-09-24 11:28
Duplicate of #3216

**Closed by khaledhosny** 2021-09-24 11:28 UTC
