### ISSUE TITLE
Directionality of regional-indicator flags in for AAT font

### ISSUE THREAD

**Issue by arenevier** [harfbuzz/harfbuzz#3314] opened 2021-12-02 01:19 UTC
This is a follow up of issue #2265 

The problem has been fixed by pull #3018  but still happens for some fonts on macos.

See https://bugs.chromium.org/p/chromium/issues/detail?id=1272436#c8 for the bug report on chromium.

I have investigated, and I believe that the root cause of the issue in the following code reversing the buffer without considering continuations: https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-aat-layout-morx-table.hh#L1040

Because of that, the regional indicators are reversed before substitution.

**Comment by behdad** [comment] 2021-12-02 01:27
Interesting. Thanks for investigating. I'll get onto it. Can you provide test case?

**Comment by arenevier** [comment] 2021-12-02 01:40
The following change seems to fix the issue for me: https://github.com/harfbuzz/harfbuzz/issues/3314

In order to reproduce, you can type the following into chrome urlbar on mac os:
data:text/html;charset=utf-8,%D7%90%F0%9F%87%BA%F0%9F%87%B8%F0%9F%87%AE%F0%9F%87%B1

It will render The letter א, a boxed U, a boxed S and the flag of Liechtenstein

(instead of the flag of US and flag of Israel)

**Comment by behdad** [comment] 2021-12-02 02:02
Copying the repro text here for simplicity:
א🇺🇸🇮🇱

**Comment by behdad** [comment] 2021-12-02 02:09
```
$ util/hb-shape /System/Library/Fonts/Apple\ Color\ Emoji.ttc א🇺🇸🇮🇱
[u1F1F1_u1F1EE=3+800|u1F1F8=1+800|u1F1FA=1+800|.notdef=0+800]
```

**Comment by jfkthame** [comment] 2021-12-03 11:09
Somewhat surprisingly, this doesn't seem to reproduce in Firefox: the example renders the two expected flags. But I haven't investigated to see exactly what we're doing differently here.

**Comment by behdad** [comment] 2021-12-03 14:26
> Somewhat surprisingly, this doesn't seem to reproduce in Firefox: the example renders the two expected flags. But I haven't investigated to see exactly what we're doing differently here.

Interesting. I remember Firefox was doing itemization differently with respect to bidi and script. Perhaps has to do with that.

**Comment by behdad** [comment] 2021-12-03 14:45
> Interesting. I remember Firefox was doing itemization differently with respect to bidi and script. Perhaps has to do with that.

In my testing, if I don't give the Hebrew Alaph to hb-shape, the problem doesn't happen.

**Comment by arenevier** [comment] 2021-12-03 17:46
Yes, Firefox does splitting differently. 

and yes, the hebrew script forces the buffer reversal in hb_ensure_native_direction

**Comment by behdad** [comment] 2022-04-06 21:47
This has caused a regression:
https://github.com/harfbuzz/harfbuzz/issues/3528

We need a narrower fix, perhaps one only affecting regional-indicators.

**Comment by behdad** [comment] 2022-04-07 19:45
Wait a second. Given that Regional-Indicators are bidi=L, why is Chrome passing them with hebrew Alaph in to HarfBuzz in the same run to begin with? I believe that's the core of the issue. CoreText is breaking runs and never shaping them together internally.

**Comment by behdad** [comment] 2022-04-07 19:47
> Wait a second. Given that Regional-Indicators are bidi=L, why is Chrome passing them with hebrew Alaph in to HarfBuzz in the same run to begin with? I believe that's the core of the issue. CoreText is breaking runs and never shaping them together internally.

@arenevier @drott

**Comment by drott** [comment] 2022-04-19 16:09
> @arenevier @drott

Filed https://bugs.chromium.org/p/chromium/issues/detail?id=1317670 and added my findings there as a basis for discussion. (In short: atm, inline layout does multiple shaping calls, with... different directions).

**Comment by behdad** [comment] 2022-04-19 20:53
> (In short: atm, inline layout does multiple shaping calls, with... different directions

That's what I expect. The question is why was the original report reported then.

**Comment by khaledhosny** [comment] 2022-04-19 21:17
I think the issue is that they have Common script, so they get resolved to Hebrew script but LTR direction, and then HarfBuzz considers their natural direction to be RTL.

**Comment by khaledhosny** [comment] 2022-04-19 21:18
I.e. similar to the issue we had with numbers in RTL scripts.

**Comment by behdad** [comment] 2022-04-19 21:30
> I think the issue is that they have Common script, so they get resolved to Hebrew script but LTR direction, and then HarfBuzz considers their natural direction to be RTL.

That's quite a possibility. Thanks. Let me check that.

**Comment by behdad** [comment] 2022-04-19 21:30
(And would be really difficult to fix another way :( )

**Comment by behdad** [comment] 2022-04-19 21:34
> > I think the issue is that they have Common script, so they get resolved to Hebrew script but LTR direction, and then HarfBuzz considers their natural direction to be RTL.
> 
> That's quite a possibility. Thanks. Let me check that.

You are right. With master:
```
$ util/hb-shape Apple\ Color\ Emoji.ttc -u U+1F1FA,U+1F1F8,U+1F1EE,U+1F1F1 --script=hebrew
[u1F1EE_u1F1F1=2+800|u1F1FA_u1F1F8=0+800]
```

If I apply this patch:
```diff
diff --git a/src/hb-aat-layout-morx-table.hh b/src/hb-aat-layout-morx-table.hh
index 2f9951092..0e2bb1d66 100644
--- a/src/hb-aat-layout-morx-table.hh
+++ b/src/hb-aat-layout-morx-table.hh
@@ -1038,12 +1038,12 @@ struct Chain
        goto skip;
 
       if (reverse)
-       _hb_ot_layout_reverse_graphemes (c->buffer);
+       hb_buffer_reverse (c->buffer);
 
       subtable->apply (c);
 
       if (reverse)
-       _hb_ot_layout_reverse_graphemes (c->buffer);
+       hb_buffer_reverse (c->buffer);
 
       (void) c->buffer->message (c->font, "end chainsubtable %d", c->lookup_index);
```
(which basically reverses the fix for this issue):
```
 util/hb-shape Apple\ Color\ Emoji.ttc -u U+1F1FA,U+1F1F8,U+1F1EE,U+1F1F1 --script=hebrew
[u1F1F1_u1F1EE=2+800|u1F1F8=0+800|u1F1FA=0+800]
```

So, the Hebrew Alaph is not being passed to HB by Chrome. It's just the script tag.

**Comment by behdad** [comment] 2022-04-20 17:09
> > > I think the issue is that they have Common script, so they get resolved to Hebrew script but LTR direction, and then HarfBuzz considers their natural direction to be RTL.
> > 
> > 
> > That's quite a possibility. Thanks. Let me check that.
> 
> You are right

I suggest fixing it like the Arabic numbers then, by hardcoding Regional-Indicators as LTR. I'll prepare a patch.

**Comment by behdad** [comment] 2022-04-20 17:46
Proper fix: https://github.com/harfbuzz/harfbuzz/pull/3539

**Closed** 2022-04-24 13:12 UTC
