### ISSUE TITLE
[sbix] hb-view returns nothing when sbix table present

### ISSUE THREAD

**Issue by simoncozens** [harfbuzz/harfbuzz#2078] opened 2019-12-15 19:20 UTC
I just tried using my [sbix test font](https://github.com/simoncozens/test-fonts/blob/master/CFF-and-SBIX.otf) with `hb-view`, and got:

```
simon@upo ~/hacks/typography/test-fonts *$ hb-shape CFF-and-SBIX.otf ABC
[A=0+949|B=1+600|.notdef=2+500]
simon@upo ~/hacks/typography/test-fonts *$ hb-view CFF-and-SBIX.otf ABC
simon@upo ~/hacks/typography/test-fonts *$ echo $?
0
```

**Comment by behdad** [comment] 2019-12-15 19:49
Currently `hb-view` tries loading glyph image using FreeType.  FreeType gives error if requested pixel size is different from all of available "strike" sizes in the font.  So, you need to pass `--font-size=??` with the right / magic numbers to `hb-view` for them to render.

We should do two things:
* Also add option to use our own PNG fetch from the font using `hb-color` API, and render the PNG onto cairo.  Maybe let's not do this now; we'll do after we also add glyph outline API.  Then one can build hb-view without FreeType completely (but with cairo).

* Load the bitmap at best available size from FreeType, and use cairo to scale it.

Actually I have a very vague memory that I made cairo do that automatically already.  Humm.  I'm very surprised now.

Can you try with latest cairo?  I mean, cairo from git master; there hasn't been a release in years...

**Comment by simoncozens** [comment] 2019-12-15 20:56
No improvement:

```
simon@upo ~/hacks/typography/test-fonts *$ hb-view --font-size=128 CFF-and-SBIX.otf A
simon@upo ~/hacks/typography/test-fonts *$ brew info cairo
cairo: stable 1.16.0 (bottled), HEAD
Vector graphics library with cross-device output support
https://cairographics.org/
/usr/local/Cellar/cairo/HEAD-f93fc72_2 (48 files, 3.5MB) *
```

**Comment by khaledhosny** [comment] 2019-12-15 22:29
Can you try on Linux, since I switched to macOS I often than not fail to get any glyph rendering from Cairo.

**Comment by behdad** [comment] 2019-12-19 22:20
Passing `--font-funcs=ot` makes it work.  Our FreeType font funcs are not set up for bitmap-only fonts currently.  Duplicate of https://github.com/harfbuzz/harfbuzz/issues/489

**Closed by behdad** 2019-12-19 22:20 UTC
