### ISSUE TITLE
Khmer: Postion of characters improper

### ISSUE THREAD

**Issue by Amritasingh0512** [harfbuzz/harfbuzz#972] opened 2018-04-12 13:04 UTC
Font Used: Khmer OS Content
Text: 

ស្រ្ត៊ៀ ស្រ្ត៊េ រ្រ
--
[KhmerOSContent-Regular.zip](https://github.com/harfbuzz/harfbuzz/files/1954173/KhmerOSContent-Regular.zip)

![4](https://user-images.githubusercontent.com/38288804/38678933-116dbe42-3e80-11e8-99a9-9436ef7e8c46.PNG)

**Comment by ebraminio** [comment] 2018-04-12 13:33
I can confirm the difference. CoreText, Uniscribe and HarfBuzz disagree which each others :)

```
HarfBuzz:
$ build/util/hb-shape KhmerOSContent-Regular.ttf -u U+179F,U+17D2,U+179A,U+17D2,U+178F,U+17CA,U+17C0,U+0020,U+179F,U+17D2,U+179A,U+17D2,U+178F,U+17CA,U+17C1,U+0020,U+179A,U+17D2,U+179A --shaper=ot
   
[glyph378=0+2680|glyph467=0+0|uni17D2_uni178F.zz02=0+0|uni17CA=0+0|uni17C0=0+580|space=7+569|glyph378=8+2680|glyph467=8+0|uni17D2_uni178F.zz02=8+0|uni17CA=8+0|uni17C1=8+580|space=15+569|uni179A=16+580|uni17D2_uni179A.zz05=16+580]

CoreText:
$ build/util/hb-shape KhmerOSContent-Regular.ttf -u U+179F,U+17D2,U+179A,U+17D2,U+178F,U+17CA,U+17C0,U+0020,U+179F,U+17D2,U+179A,U+17D2,U+178F,U+17CA,U+17C1,U+0020,U+179A,U+17D2,U+179A --shaper=coretext 

[glyph378=0+2680|glyph467=0+0|uni17D2_uni178F.zz02=2+0|uni17CA=4+0|uni17C0=4+580|space=7+569|glyph378=8+2680|glyph467=8+0|uni17D2_uni178F.zz02=10+0|uni17CA=12+0|uni17C1=12+580|space=15+569|uni179A=16+580|uni17D2_uni179A.zz05=16+580

Uniscribe:
$ WINEDLLOVERRIDES="usp10=n" wine winbuild/util/hb-shape.exe KhmerOSContent-Regular.ttf -u U+179F,U+17D2,U+179A,U+17D2,U+178F,U+17CA,U+17C0,U+0020,U+179F,U+17D2,U+179A,U+17D2,U+178F,U+17CA,U+17C1,U+0020,U+179A,U+17D2,U+179A --shaper=uniscribe

[uni17C1=0+580|glyph192=0+580|uni179F=0+2100|uni17D2_uni178F.zz02=0+0|uni17CA=0+0|uni17C0=0+580|space=7+569|uni17C1=8+580|glyph192=8+580|uni179F=8+2100|uni17D2_uni178F.zz02=8+0|uni17CA=8+0|space=15+569|uni17D2_uni179A.zz05=16+580|uni179A=16+580]
```

**Comment by olivierberten** [comment] 2018-04-24 19:59
Please notice coeng ro (U+17D2,U+179A) should always be typed after any other coeng, which means the 2 subscript consonants should be switched in the first 2 clusters.

**Comment by behdad** [comment] 2018-04-26 23:15
Link to font please?

**Comment by olivierberten** [comment] 2018-04-27 09:54
You can also spot that bug with most khmer Google Fonts
![bug972-googlefonts](https://user-images.githubusercontent.com/213117/39356990-c32ebab8-4a11-11e8-941e-23038004f40f.png)

**Comment by Richard57** [comment] 2018-06-05 02:11
Olivierberten said, "Please notice coeng ro (U+17D2,U+179A) should always be typed after any other coeng".

While that is true for Khmer words, how then should one write the Sanskrit cluster 'grv'?

**Comment by olivierberten** [comment] 2018-06-05 04:55
Good question... @danhhong @sovichet @sbbic @MakaraSok @mcdurdin @punchcutter ?
Problem is there's no way for OpenType to know what's the typed order...

**Comment by behdad** [comment] 2018-06-05 05:02
That's what the 'cfar' feature is for.

**Comment by Richard57** [comment] 2018-06-05 18:20
Whether the feature works depends on the meaning of "followed".  If "followed" means in code point order as opposed to visual order it could work, but I see no promise of any step actually working on Windows.  Mind you, one can read the specification for Khmer as saying that "pres" is invoked only if there is another subscript on the consonant - I am not sure I believe that.  There's no documentation to assure us that "cfar" is actually invoked on Windows.

The best prospect of determining the type of COENG RO seems to be to do something with "ccmp", but I'm not sure it would work.  In the USE, I've been deliberately leaving ghosts behind after preposed vowels move.  As always, it would be nice to have a usable description of Windows processing.

**Comment by behdad** [comment] 2018-06-06 22:51
> After reading https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#a-namecfar-idcfaratag-cfar I still don't see how rendering engine would know whether the COENG VO has been typed before or after COENG RO.

In one case cfar feature is applied to COENG VO, in other case it isn't. Windows does this. That's how I discovered it in the first place. From the HarfBuzz commit that implemented it:

commit 0201e0a4649ad5b607e50bcb9605e7a5b7143812
Author: Behdad Esfahbod <behdad@behdad.org>
Date:   Tue Jul 17 13:55:10 2012 -0400

    [Indic] Apply 'cfar' for Khmer
    
    Mark stuff after a pre-base reordering Ro 'cfar'.  Used in Khmer.
    This allows distinguishing the following cases with MS Khmer fonts:
    
      U+1784,U+17D2,U+179A,U+17D2,U+1782
      U+1784,U+17D2,U+1782,U+17D2,U+179A

**Comment by olivierberten** [comment] 2018-06-07 06:29
I obviously misunderstood :)

Thanks for the info! DaunPenh is the only font to use that feature... Most probably because it's not documented at https://docs.microsoft.com/en-us/typography/script-development/khmer
@n8willis I guess this is a perfect candidate for https://github.com/n8willis/opentype-shaping-documents/

Nokia Pure S40 KHMR also has cfar but uses it the same way as blws for narrower second subscript so there's no way to distinguish them.

**Comment by behdad** [comment] 2018-07-31 19:17
Fixed by https://github.com/harfbuzz/harfbuzz/commit/1a96cc825dc9c8e3b6eef1403fe0864a1cfc0245

**Closed by behdad** 2018-07-31 19:17 UTC
Labels: Adobe
