### ISSUE TITLE
Stylistic alternates feature not working with DAveau font

### ISSUE THREAD

**Issue by sid-wr** [harfbuzz/harfbuzz#4898] opened 2024-10-14 08:26 UTC
Hi

For _**DAveau**_ font, the Stylistic Alternates OpenType feature doesn't seem to be working with HarfBuzz even though the stylistic alternate glyphs are present in this font.

The **hb-view** tool is generating same output for the example text without v/s with Stylistic alternates

1) Without Stylistic Alternates
```
hb-view.exe daveauregular.otf --text="A" --output-file="DAveau-without-stylistic-alternates.png"
```
![DAveau-without-stylistic-alternates](https://github.com/user-attachments/assets/26ecaafe-53c3-4a06-b3d1-514757b5294a)

2) With Stylistic Alternates
```
hb-view.exe daveauregular.otf --features="ss01" --text="A" --output-file="DAveau-with-ss01.png"
hb-view.exe daveauregular.otf --features="ss02" --text="A" --output-file="DAveau-with-ss02.png"
hb-view.exe daveauregular.otf --features="ss03" --text="A" --output-file="DAveau-with-ss03.png"
hb-view.exe daveauregular.otf --features="ss04" --text="A" --output-file="DAveau-with-ss04.png"
hb-view.exe daveauregular.otf --features="ss05" --text="A" --output-file="DAveau-with-ss05.png"
hb-view.exe daveauregular.otf --features="ss06" --text="A" --output-file="DAveau-with-ss06.png"
hb-view.exe daveauregular.otf --features="ss07" --text="A" --output-file="DAveau-with-ss07.png"
hb-view.exe daveauregular.otf --features="ss08" --text="A" --output-file="DAveau-with-ss08.png"
hb-view.exe daveauregular.otf --features="ss09" --text="A" --output-file="DAveau-with-ss09.png"
hb-view.exe daveauregular.otf --features="ss10" --text="A" --output-file="DAveau-with-ss10.png"
hb-view.exe daveauregular.otf --features="ss11" --text="A" --output-file="DAveau-with-ss11.png"
hb-view.exe daveauregular.otf --features="ss12" --text="A" --output-file="DAveau-with-ss12.png"
hb-view.exe daveauregular.otf --features="ss13" --text="A" --output-file="DAveau-with-ss13.png"
hb-view.exe daveauregular.otf --features="ss14" --text="A" --output-file="DAveau-with-ss14.png"
hb-view.exe daveauregular.otf --features="ss15" --text="A" --output-file="DAveau-with-ss15.png"
hb-view.exe daveauregular.otf --features="ss16" --text="A" --output-file="DAveau-with-ss16.png"
hb-view.exe daveauregular.otf --features="ss17" --text="A" --output-file="DAveau-with-ss17.png"
hb-view.exe daveauregular.otf --features="ss18" --text="A" --output-file="DAveau-with-ss18.png"
hb-view.exe daveauregular.otf --features="ss19" --text="A" --output-file="DAveau-with-ss19.png"
hb-view.exe daveauregular.otf --features="ss20" --text="A" --output-file="DAveau-with-ss20.png"
```
![DAveau-with-ss01](https://github.com/user-attachments/assets/0c00db0a-47a5-4b60-a0fb-e035e25d7e50)

Also confirmed the same from **hb-shape** tool

1) Without Stylistic Alternates
```
hb-shape.exe daveauregular.otf --text="A"
[A=0+921]
```

2) With Stylistic Alternates
```
hb-shape.exe daveauregular.otf --text="A" --features="ss01"
[A=0+921]
hb-shape.exe daveauregular.otf --text="A" --features="ss02"
[A=0+921]
hb-shape.exe daveauregular.otf --text="A" --features="ss03"
[A=0+921]
hb-shape.exe daveauregular.otf --text="A" --features="ss04"
[A=0+921]
hb-shape.exe daveauregular.otf --text="A" --features="ss05"
[A=0+921]
hb-shape.exe daveauregular.otf --text="A" --features="ss06"
[A=0+921]
hb-shape.exe daveauregular.otf --text="A" --features="ss07"
[A=0+921]
hb-shape.exe daveauregular.otf --text="A" --features="ss08"
[A=0+921]
hb-shape.exe daveauregular.otf --text="A" --features="ss09"
[A=0+921]
hb-shape.exe daveauregular.otf --text="A" --features="ss10"
[A=0+921]
hb-shape.exe daveauregular.otf --text="A" --features="ss11"
[A=0+921]
hb-shape.exe daveauregular.otf --text="A" --features="ss12"
[A=0+921]
hb-shape.exe daveauregular.otf --text="A" --features="ss13"
[A=0+921]
hb-shape.exe daveauregular.otf --text="A" --features="ss14"
[A=0+921]
hb-shape.exe daveauregular.otf --text="A" --features="ss15"
[A=0+921]
hb-shape.exe daveauregular.otf --text="A" --features="ss16"
[A=0+921]
hb-shape.exe daveauregular.otf --text="A" --features="ss17"
[A=0+921]
hb-shape.exe daveauregular.otf --text="A" --features="ss18"
[A=0+921]
hb-shape.exe daveauregular.otf --text="A" --features="ss19"
[A=0+921]
hb-shape.exe daveauregular.otf --text="A" --features="ss20"
[A=0+921]
```

Both are generating same glyph ID in the output

Please help

**Comment by khaledhosny** [comment] 2024-10-15 08:35
Duplicate of #4897

**Closed by khaledhosny** 2024-10-15 08:35 UTC
