### ISSUE TITLE
deprecated graphite functions

### ISSUE THREAD

**Issue by vtorri** [harfbuzz/harfbuzz#2810] opened 2021-01-12 06:31 UTC
i have the latest graphite lib and a function is deprecated : 

```
../src/hb-graphite2.cc: In function 'hb_graphite2_face_data_t* _hb_graphite2_shaper_face_data_create(hb_face_t*)':
../src/hb-graphite2.cc:131:81: warning: 'gr_face* gr_make_face(const void*, gr_get_table_fn, unsigned int)' is deprecated [-Wdeprecated-declarations]
  131 |   data->grface = gr_make_face (data, &hb_graphite2_get_table, gr_face_preloadAll);
      |                                                                                 ^
In file included from ../src/hb-graphite2.h:31,
                 from ../src/hb-graphite2.cc:35:
C:/Documents/msys2/opt/ewpi_64/include/graphite2/Font.h:143:29: note: declared here
  143 | GR2_DEPRECATED_API gr_face* gr_make_face(const void* appFaceHandle/*non-NULL*/, gr_get_table_fn getTable, unsigned int faceOptions);
      |                             ^~~~~~~~~~~~
```

**Comment by khaledhosny** [comment] 2021-01-12 09:30
See https://github.com/harfbuzz/harfbuzz/issues/1829 where the use of updated API was reverted.

**Comment by khaledhosny** [comment] 2021-01-12 09:31
Duplicate of #2592

**Closed by khaledhosny** 2021-01-12 09:31 UTC
