### ISSUE TITLE
compilation failure with ICU 76.1: 'redundant redeclaration of 'int32_t '

### ISSUE THREAD

**Issue by vtorri** [harfbuzz/harfbuzz#4921] opened 2024-10-29 07:35 UTC
Using the latest ICU (as of today), here is the error:

```

FAILED: src/libharfbuzz-icu-0.dll.p/hb-icu.cc.obj 

"x86_64-w64-mingw32-g++" "-Isrc/libharfbuzz-icu-0.dll.p" "-Isrc" "-I../src" "-I." "-I.." "-IC:/Documents/msys2/home/vincent.torri/ewpi_64/include" "-fdiagnostics-color=always" "-D_GLIBCXX_ASSERTIONS=1" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-std=c++17" "-fno-exceptions" "-O3" "-fno-exceptions" "-fno-rtti" "-fno-threadsafe-statics" "-fvisibility-inlines-hidden" "-Wa,-mbig-obj" "-DHAVE_CONFIG_H" "-O2" "-pipe" "-march=x86-64" "-Wno-non-virtual-dtor" -MD -MQ src/libharfbuzz-icu-0.dll.p/hb-icu.cc.obj -MF "src/libharfbuzz-icu-0.dll.p/hb-icu.cc.obj.d" -o src/libharfbuzz-icu-0.dll.p/hb-icu.cc.obj "-c" ../src/hb-icu.cc
In file included from C:/Documents/msys2/home/vincent.torri/ewpi_64/include/unicode/platform.h:25,
                 from C:/Documents/msys2/home/vincent.torri/ewpi_64/include/unicode/ptypes.h:46,
                 from C:/Documents/msys2/home/vincent.torri/ewpi_64/include/unicode/umachine.h:46,
                 from C:/Documents/msys2/home/vincent.torri/ewpi_64/include/unicode/utypes.h:38,
                 from C:/Documents/msys2/home/vincent.torri/ewpi_64/include/unicode/uscript.h:20,
                 from ../src/hb-icu.h:34,
                 from ../src/hb-icu.cc:34:
C:/Documents/msys2/home/vincent.torri/ewpi_64/include/unicode/urename.h:393:43: error: redundant redeclaration of 'int32_t u_strlen_76(const UChar*)' in same scope [-Werror=redundant-decls]
  393 | #define u_strlen U_ICU_ENTRY_POINT_RENAME(u_strlen)
      |                                           ^~~~~~~~
C:/Documents/msys2/home/vincent.torri/ewpi_64/include/unicode/uvernum.h:121:50: note: in definition of macro 'U_DEF_ICU_ENTRY_POINT_RENAME'
  121 | #       define U_DEF_ICU_ENTRY_POINT_RENAME(x,y) x ## y
      |                                                  ^
C:/Documents/msys2/home/vincent.torri/ewpi_64/include/unicode/uvernum.h:123:47: note: in expansion of macro 'U_DEF2_ICU_ENTRY_POINT_RENAME'
  123 | #       define U_ICU_ENTRY_POINT_RENAME(x)    U_DEF2_ICU_ENTRY_POINT_RENAME(x,U_ICU_VERSION_SUFFIX)
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Documents/msys2/home/vincent.torri/ewpi_64/include/unicode/urename.h:393:18: note: in expansion of macro 'U_ICU_ENTRY_POINT_RENAME'
  393 | #define u_strlen U_ICU_ENTRY_POINT_RENAME(u_strlen)
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~
C:/Documents/msys2/home/vincent.torri/ewpi_64/include/unicode/ustring.h:93:1: note: in expansion of macro 'u_strlen'
   93 | u_strlen(const UChar *s);
      | ^~~~~~~~
C:/Documents/msys2/home/vincent.torri/ewpi_64/include/unicode/urename.h:393:43: note: previous declaration of 'int32_t u_strlen_76(const UChar*)'
  393 | #define u_strlen U_ICU_ENTRY_POINT_RENAME(u_strlen)
      |                                           ^~~~~~~~
C:/Documents/msys2/home/vincent.torri/ewpi_64/include/unicode/uvernum.h:121:50: note: in definition of macro 'U_DEF_ICU_ENTRY_POINT_RENAME'
  121 | #       define U_DEF_ICU_ENTRY_POINT_RENAME(x,y) x ## y
      |                                                  ^
C:/Documents/msys2/home/vincent.torri/ewpi_64/include/unicode/uvernum.h:123:47: note: in expansion of macro 'U_DEF2_ICU_ENTRY_POINT_RENAME'
  123 | #       define U_ICU_ENTRY_POINT_RENAME(x)    U_DEF2_ICU_ENTRY_POINT_RENAME(x,U_ICU_VERSION_SUFFIX)
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Documents/msys2/home/vincent.torri/ewpi_64/include/unicode/urename.h:393:18: note: in expansion of macro 'U_ICU_ENTRY_POINT_RENAME'
  393 | #define u_strlen U_ICU_ENTRY_POINT_RENAME(u_strlen)
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~
C:/Documents/msys2/home/vincent.torri/ewpi_64/include/unicode/unistr.h:51:26: note: in expansion of macro 'u_strlen'
   51 | U_CAPI int32_t U_EXPORT2 u_strlen(const UChar *s);
      |                          ^~~~~~~~
In file included from C:/Documents/msys2/home/vincent.torri/ewpi_64/include/unicode/utf.h:218,
                 from C:/Documents/msys2/home/vincent.torri/ewpi_64/include/unicode/utypes.h:44:
../src/hb-icu.cc: In function 'hb_bool_t hb_icu_unicode_decompose(hb_unicode_funcs_t*, hb_codepoint_t, hb_codepoint_t*, hb_codepoint_t*, void*)':
C:/Documents/msys2/home/vincent.torri/ewpi_64/include/unicode/utf16.h:173:48: warning: array subscript -1 is below array bounds of 'UChar [4]' {aka 'char16_t [4]'} [-Warray-bounds=]
  173 |             (c)=U16_GET_SUPPLEMENTARY((s)[(i)-1], (c)); \
      |                                                ^
C:/Documents/msys2/home/vincent.torri/ewpi_64/include/unicode/utf16.h:113:17: note: in definition of macro 'U16_GET_SUPPLEMENTARY'

  113 |     (((UChar32)(lead)<<10UL)+(UChar32)(trail)-U16_SURROGATE_OFFSET)

      |                 ^~~~

../src/hb-icu.cc:223:5: note: in expansion of macro 'U16_GET_UNSAFE'

  223 |     U16_GET_UNSAFE (decomposed, 0, *a);

      |     ^~~~~~~~~~~~~~

../src/hb-icu.cc:213:9: note: while referencing 'decomposed'

  213 |   UChar decomposed[4];

      |         ^~~~~~~~~~

cc1plus.exe: some warnings being treated as errors
```

**Comment by khaledhosny** [comment] 2024-10-29 07:41
Duplicate of #4915

**Closed by khaledhosny** 2024-10-29 07:41 UTC
