### ISSUE TITLE
Khmer Sign Coeng

### ISSUE THREAD

**Issue by Ali-Alzyoud** [harfbuzz/harfbuzz#1630] opened 2019-03-27 14:00 UTC
Following Unicode Character does not seems to render properly (◌្) with latest Harfbuzz
https://www.compart.com/en/unicode/U+17D2 

This project show the issue (modified harfbuzz tutorial):
https://github.com/Ali-Alzyoud/Harfbuzz-khmer.git

if you run the project with latest harfbuzz you will not get right results.
but if you run with harfbuzz (git checkout 82e6bf8e) you will get right results.

After some investigations : 
Old harfbuzz 
when you add '\u17D2' to buffer and shape it will buffer will contains 'uni25CC' + 'uni17D2'
New harfbuzz
when you add '\u17D2' to buffer and shape it will buffer will contains only 'uni17D2'

**Comment by khaledhosny** [comment] 2019-03-27 14:31
Duplicate of #1541

**Closed by khaledhosny** 2019-03-27 14:31 UTC
