### ISSUE TITLE
Ideographic spaces are synthesized using non-CJK fonts in Blink

### ISSUE THREAD

**Issue by kojiishi** [harfbuzz/harfbuzz#2889] opened 2021-03-07 14:30 UTC
When author specifies non-CJK fonts before CJK fonts in the `font-family` property in Blink, following 3 symptoms are observed. 

Originally found the symptom 1, then found this is probably related with #2885, and found other symptoms. These symptoms are not seen in Gecko. I'm not sure whether this is a Blink issue or not. Any advice is very much appreciated in advance. /cc @drott

**1. GPOS that involves U+3000 are not applied**

The font in [this test page](https://jsbin.com/mosomej/edit?html,output) has a GPOS feature for U+3000 using format 2 and format 8.

**2. Width of U+3000 in the fonts are ignored**

Ideographic Spaces are meant to match Kana and Ideographic characters in the fonts. It is usually 1em, but not always so. An example when Kana and Ideographic do not have the same advance can be observed in [a test page](https://jsbin.com/quqibi/edit?html,output), or by using `hb-shape`:
```sh
% hb-shape msgothic.ttc --face-index 0 -u 3000
[gid2057=0+256]
% hb-shape msgothic.ttc --face-index 1 -u 3000
[gid20621=0+170]
% hb-shape msgothic.ttc --face-index 2 -u 3000
[gid18103=0+170]
```
It is also seen in some news paper fonts, such as [Motoya Newspaper Mincho/Gothic](http://www.motoyafont.jp/font-list/news.html) or [Font Garage AFS series](https://font.designers-garage.jp/products/detail/7792).

**3. Pure CJK runs are split at Ideographic spaces in Blink**

In the following example, Blink decides to split the run and use Arial to render U+3000. No visual differences in this case, but slightly less efficient as it is rendered as two separate runs.
```html
<p style="font-family: Arial, 'MS Gothic'">&#x3031;&#x3000;</p>
```

**Comment by drott** [comment] 2021-03-08 09:32
What's your expectation exactly? Can I assume you're suggesting HarfBuzz should not attempt to synthesise U+3000 for fonts higher in the stack that don't have it in their CMAP? This would be done in order to avoid, 1) breaking GPOS with U+3000 2) custom U+3000 width 3) ShapeResult fragmentation. 

In general, the approach is that we use as many glyphs as possible from the fonts in order of the font stack - of course with synthetisation we're in a position where we pretend the primary font had the space glyphs - which is suboptimal in this case. What could be a good algorithmic way to control it? - One way perhaps: If the shape result `hb_buffer_t` only manages to produce synthesised glyphs and hasn't found real ones - perhaps it should drop those synthesized ones then as well? - This could be decided on the HarfBuzz level or in a postprocessing stage in Blink. 

@jfkthame for opinions? 

I believe Gecko doesn't show this behaviour because of different font segmentation to ours. We do grapheme cluster based fallback and pass things to HarfBuzz to decide to what extent the font can be used.

**Comment by jfkthame** [comment] 2021-03-08 09:53
Right, Gecko doesn't currently use HarfBuzz to drive the font fallback process in the same way, it works more directly from the cmap coverage. In some cases this doesn't work as well, and I've wondered about moving in that direction -- but here's an example where the HB-based approach actually gives an unwanted result.

Maybe a possible mitigation would be to check for whitespace characters and always continue the current font run for these, on the grounds that they can be synthesized and don't depend on actual font support? So spaces would always use the font of the immediately-preceding text. Though this could also give less-than-ideal results at run boundaries, if the "main" and "fallback" fonts have noticeably different space widths.

**Comment by jfkthame** [comment] 2021-03-08 09:56
Better, probably, would be a rule that whitespace characters adopt the same font as their surrounding text (rather than applying normal font selection behavior starting with the first font in the stack) if the font chosen for the preceding and following text is the same. But that involves a lookahead in addition to the current state, so may not be practical to implement.

**Comment by kojiishi** [comment] 2021-03-19 07:12
Thank you @drott and @jfkthame, all what you wrote were really helpful.

> What's your expectation exactly?

Sorry that was not clear. We talked but for the record; this came up right after #2885, saw its from the similar root cause. I understand what we do and its benefits, but I wanted to have exerts' opinion on this one too, including how to fix and whether this should be fixed in HarfBuzz or in Blink.

Also IIUC we're looking forward to define run segmentations. I thought these symptoms may be one of inputs to the discussion.

> Better, probably, would be a rule that whitespace characters adopt the same font as their surrounding text

I agree, the rule for spaces should be similar to what we do for punctuation/symbols (common scripts). Even for the performance perspective, splitting runs at spaces is probably slightly negative.

One more thing I'd like us to take into account is that, among the [several Unicode White Spaces](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=[:White_Space=Yes:]), U+1680 OGHAM SPACE MARK and U+3000 IDEOGRPAHIC SPACE are the only script-specific spaces.

I think these script-specific spaces, even if they are surrounded by Latin characters, should be biased to these scripts. I don't know much about OGHAM case but systems that support composite fonts per scripts/script-groups such as OpenOffice or Japanese TeX, use CJK font slot for IDEOGRPAHIC SPACE.

I see HarfBuzz does not synthesize U+1680 OGHAM SPACE MARK, maybe because it has inks? I haven't understood the HarfBuzz logic that determines white spaces to synthesize, may be it's using different Unicode properties, but I think U+3000 IDEOGRPAHIC SPACE should be in the script-specific spaces, same group as OGHAM, even though it usually doesn't have inks.

Since the actual symptom only appears in Blink at this moment, as I wrote above, I'm fine to fix this in Blink, but further consideration for U+3000 IDEOGRPAHIC SPACE would be greatly appreciated.

**Comment by khaledhosny** [comment] 2021-07-26 03:16
U+1680 OGHAM SPACE MARK has ink, so HarfBuzz can’t synthesis it. The current issue should be fixed in Chrome, since it can happen even without HarfBuzz synthesizing space e.g. if the first font happened to have U+3000 IDEOGRPAHIC SPACE but not thee sorrounding ideographs. Chrome should try one of @jfkthame suggestions above.

**Comment by khaledhosny** [comment] 2021-07-26 03:21
The issue is also more general. What happens if you have ARABIC space ARABIC and the first font on the list supports space (as nearly every font does) but not Arabic? Do you end with three runs, and space glyph that might be too wide or too narrow for the Arabic text?

**Comment by kojiishi** [comment] 2021-07-26 04:46
We've added a workaround for U+3000 IDEOGRPAHIC SPACE that if the result is a space glyph, we consider the glyph is missing. It may misbehave if U+0020 and U+3000 share a glyph id, but I've never seen such fonts in the real world.

I agree "ARABIC space ARABIC" case is more complicated because U+0020 is shared by multiple scripts. It has, as Jonathan pointed out, the same challenge as symbols and punctuations.

**Comment by khaledhosny** [comment] 2021-07-26 05:30
Closing then, I don’t think we need to change anything in HarfBuzz.

**Closed by khaledhosny** 2021-07-26 05:30 UTC
