### ISSUE TITLE
GPOS regression

### ISSUE THREAD

**Issue by punchcutter** [harfbuzz/harfbuzz#2576] opened 2020-07-18 05:59 UTC
With Noto Grantha Sans and Serif all blwm seems to be broken after this commit: https://github.com/harfbuzz/harfbuzz/commit/f4cd99f28eefe695b86876736166fd119e22e04e

A couple test strings:
𑌕𑍍𑌕𑌂 
U+11315 U+1134D U+11315 U+11302
𑌸𑍍𑌪𑍍𑌰𑌷
U+11338 U+1134D U+1132A U+1134D U+11330 U+11337 
𑌹𑍍𑌖
U+11339 U+1134D U+11316
![examples](https://user-images.githubusercontent.com/11257204/87845925-c255e680-c880-11ea-87e8-e733aef423ec.jpg)

[NotoSansGrantha-Regular.otf.zip](https://github.com/harfbuzz/harfbuzz/files/4941129/NotoSansGrantha-Regular.otf.zip)

**Comment by simoncozens** [comment] 2020-07-22 08:55
Can you check if #2553 fixes this?

**Comment by behdad** [comment] 2020-07-22 14:43
I think I know what going on. Will comment today.

**Comment by simoncozens** [comment] 2020-07-29 09:00
I know you've been busy with moves and stuff, but any progress on this?

**Comment by khaledhosny** [comment] 2020-08-07 14:26
Duplicate of #2516

**Closed by khaledhosny** 2020-08-07 14:26 UTC

**Comment by behdad** [comment] 2020-08-08 19:53
Can you confirm that your font doesn't have GDEF?!  I'm really surprised.

**Comment by behdad** [comment] 2020-08-08 19:54
> I know you've been busy with moves and stuff, but any progress on this?

I'm sorry. I just opened laptop after over two weeks...  Let me follow up on dup issue.

**Comment by simoncozens** [comment] 2020-08-08 19:54
File linked above does have GDEF:

```
$ ttx -l ~/Downloads/NotoSansGrantha-Regular.otf
Listing table info for "/Users/simon/Downloads/NotoSansGrantha-Regular.otf":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    CFF   0xEE9068BA     44478      2788
    GDEF  0x241F218D       390     47268
```
