### ISSUE TITLE
Rocky HVAR handling for Avenir Next

### ISSUE THREAD

**Issue by brawer** [harfbuzz/harfbuzz#433] opened 2017-03-01 21:48 UTC
@taylorb-monotype sent me an e-mail:

> We have just posted a new demo variable font to
> https://github.com/Monotype/Monotype_prototype_variable_fonts/tree/master/AvenirNext
>
> I downloaded and built FontView from the master branch at https://github.com/googlei18n/fontview
>
> When I try our new demo font in FontView there are abrupt transitions at some of the intermediate weights as I move the slider across the weight range. These appear to be at weights related to the input instances. It should change smoothly as you move across the weight range.
>
> We do not see this behavior in a tool of ours based on FreeType 2.7.1. Would you mind seeing if you see the same behavior? Any idea what might be happening?

The current FontView master branch [uses](https://github.com/googlei18n/fontview/tree/master/src/third_party) HarfBuzz 1.4.2, which was cut after https://github.com/behdad/harfbuzz/commit/79e8e27ffd3da29ca27d3aebd2ef425bf1cb7f9d. This might be a HarfBuzz bug?

**Comment by behdad** [comment] 2017-03-01 22:00
You use hb-ft font funcs, right? Unlikely that it's HB bug. Have you reproduced yourself?

**Comment by brawer** [comment] 2017-03-02 01:07
Yes, I can reproduce this. The code passes a FreeType FT_Face to Raqm:
https://github.com/googlei18n/fontview/blob/master/src/fontview/sample_text.cpp#L169

**Comment by punchcutter** [comment] 2017-03-02 06:34
This particular font only goes from 400-900 on the weight axis, but it looks like fontview is assuming 0-1000? I added the wxSL_LABELS to the wxSlider to see what values are there. 0 is equivalent to the 400 weight and 1000 is equivalent to the 900 weight. It bumps at the two intermediate weights (Medium and Bold) which appear at 200 and 600 on this 0-1000 scale. If you choose Medium from the instance pulldown it should be 500, but it sets to 200. Bold should be 700, but it sets to 600 on this scale.

**Comment by behdad** [comment] 2017-04-04 07:50
Someone (other than me) needs to debug this.

**Comment by KrasnayaPloshchad** [comment] 2017-06-12 17:22
> This particular font only goes from 400-900 on the weight axis, but it looks like fontview is assuming 0-1000?

If so, fontview should be improved to honor font designer’s wishes.

**Comment by behdad** [comment] 2018-01-05 11:20
There was a bug in FreeType with out-of-range axis values.  We fixed that.  I'm guessing that was it. Closing for now until someone can reproduce again.

**Closed by behdad** 2018-01-05 11:20 UTC
Labels: bug
