### ISSUE TITLE
Incorrect Sinhala glyphs & rendering with recent HarfBuzz versions

### ISSUE THREAD

**Issue by sid-wr** [harfbuzz/harfbuzz#4276] opened 2023-06-12 08:49 UTC
Hi,
With the **hb-view** Win64 tool from HarfBuzz **7.3.0**, there are some severe rendering breaks for **_**Sinhala**_** input text as follows:

1)
```
hb-view.exe NotoSerifSinhala-Regular.ttf -u "U+0DC0U+0DDBU+0DAFU+0DCAU+200DU+0DBAU+0DC0U+0DBBU+0DBAU+0DCF" --output-file="file1.png"
```
Please find the behaviour difference in HarfBuzz 4.3.0 v/s 7.3.0:
![sinhala-1](https://github.com/harfbuzz/harfbuzz/assets/136314541/c9a7396a-4f4b-4ce6-8f6f-7e602cb6a92f)

2)
```
hb-view.exe NotoSerifSinhala-Regular.ttf -u "U+0DCFU+0020U+0D95U+0DCFU+0DCFU+0020U+0DD2U+0020U+0D95U+0DD2U+0DD2U+0020U+0DCAU+0020U+0D95U+0DCAU+0DCAU+0D95U+0020U+0D83U+0020U+0D95U+0D83U+0D83U+0020U+0D85U+0DDCU+0020U+0D95U+0D83U+0D82U+0020U+0D95U+0D82U+0D83U+0020U+0D82U+0020U+0D95U+0D82U+0D82" --output-file="file2.png"
```
Please find the behaviour difference in HarfBuzz 4.3.0 v/s 7.3.0:
![sinhala-2](https://github.com/harfbuzz/harfbuzz/assets/136314541/db3f3044-6e18-4dd2-9d5a-fa8fc4c464c1)

On further exploring, found that this issue is coming since HarfBuzz 4.4.0 (was working fine before that version)

Can you please look at it?
Thanks

**Comment by khaledhosny** [comment] 2023-06-12 08:57
Duplicate of #3725

**Closed by khaledhosny** 2023-06-12 08:57 UTC

**Comment by sid-wr** [comment] 2023-06-16 15:41
Hi @khaledhosny 
Thanks for the related URL. After upgrading the NotoSerifSinhala font to the latest version, the glyphs overlap issue is resolved.

However, for some other examples, the diacritics & dotted circles issue seems to be still there.
I tried **hb-view** of HarfBuzz **4.3.0** v/s **7.3.0** for multiple fonts.
**There seems to be rendering improvements in v7.3.0, but degradation in some places as well**

PFA the following test cases and the related snapshots:

1)```-u "U+0DCFU+0020U+0D95U+0DCFU+0DCFU+0020U+0DD2U+0020U+0D95U+0DD2U+0DD2U+0020U+0DCAU+0020U+0D95U+0DCAU+0DCAU+0D95U+0020U+0D83U+0020U+0D95U+0D83U+0D83U+0020U+0D85U+0DDCU+0020U+0D95U+0D83U+0D82U+0020U+0D95U+0D82U+0D83U+0020U+0D82U+0020U+0D95U+0D82U+0D82"```
![Example 1](https://github.com/harfbuzz/harfbuzz/assets/136314541/c1e81b28-03e9-4e96-9bad-cc7b7b7e9724)

2)```-u "U+0DBBU+0DCAU+200DU+0D9AU+0DCFU+0020U+0DBBU+0DCAU+200DU+0D9AU+0DD0U+0020U+0DBBU+0DCAU+200DU+0D9AU+0DD1U+0020U+0DBBU+0DCAU+200DU+0D9AU+0DD2U+0020U+0DBBU+0DCAU+200DU+0D9AU+0DD3U+0020U+0DBBU+0DCAU+200DU+0D9AU+0DD4U+0020U+0DBBU+0DCAU+200DU+0D9AU+0DD6U+0020U+0DBBU+0DCAU+200DU+0D9AU+0DD8U+0020U+0DBBU+0DCAU+200DU+0D9AU+0DD9U+0020U+0DBBU+0DCAU+200DU+0D9AU+0DDAU+0020U+0DBBU+0DCAU+200DU+0D9AU+0DDBU+0020U+0DBBU+0DCAU+200DU+0D9AU+0DDCU+0020U+0DBBU+0DCAU+200DU+0D9AU+0DDDU+0020U+0DBBU+0DCAU+200DU+0D9AU+0DDEU+0020U+0DBBU+0DCAU+200DU+0D9AU+0DDFU+0020U+0DBBU+0DCAU+200DU+0D9AU+0DF2"```
![Example 2](https://github.com/harfbuzz/harfbuzz/assets/136314541/a7fb80ec-773d-4ddb-b945-67341830bb83)

3)```-u "U+0DBBU+0DCAU+200DU+0DBAU+0DCAU+200DU+0DBAU+0020U+0020U+0D9AU+0DCFU+0DBBU+0DCAU+200DU+0DBAU+0DCAU+200DU+0DBAU+0DCFU+0DBDU+0DBAU+0020U+0DB8U+0DC4U+0DCFU+0DA0U+0DCFU+0DBBU+0DCAU+200DU+0DBAU+0DCAU+200DU+0DBA"```
![Example 3](https://github.com/harfbuzz/harfbuzz/assets/136314541/cf3ff7fb-c3a0-4fca-b72d-11f51e9aa2cc)

Can you please look at it?
Thanks

**Comment by behdad** [comment] 2023-06-16 16:54
> **There seems to be rendering improvements in v7.3.0, but degradation in some places as well**

Please open new issues for each of them, ideally with NotoSansSinhala and the shortest string that reproduces the problem.

**Comment by sid-wr** [comment] 2023-06-20 10:59
As suggested, I have logged 3 new issues:
- https://github.com/harfbuzz/harfbuzz/issues/4284
- https://github.com/harfbuzz/harfbuzz/issues/4285
- https://github.com/harfbuzz/harfbuzz/issues/4286
