### ISSUE TITLE
A WebAssembly version of HarfBuzz

### ISSUE THREAD

**Issue by photopea** [harfbuzz/harfbuzz#1633] opened 2019-03-28 10:49 UTC
Hi guys, I am developing a free web-based photo editor www.Photopea.com , which is used by around 100 000 people a day. It lets people do image editing, including inserting text into a picture.

As there is no sufficient OpenType parser and layout engine in Javascript, I made my own called [Typr.js](https://github.com/photopea/Typr.js). It is quite advanced and can handle e.g. Arabic text. I also use [this JS implementation of BIDI algorithm](https://github.com/bbc/unicode-bidirectional). 

As more and more people use Photopea, I have to extend Typr.js . Currently, I am adding the support for Urdu and Khmer layout. I am often staring at OpenType specification for 5 - 10 hours, without writing a single line of code, only trying to understand what they mean. I would be more than happy to drop Typr.js and use an alternative, if there was any.

Would you be able to provide a WebAssembly version of your library to the public, while documenting it and maintaining it? I am ready to pay 5k - 10k USD for it. It is also important, that the library is not too large (e.g. 150-200kB zipped), as every person has to download it when starting Photopea.

**Comment by ebraminio** [comment] 2019-03-28 11:55
Exactly what I am thinking about everyday! Well harfbuzz, despite doing a complicated thing itself, has a simple core API itself and the only thing matters about it is hb_shape(). Here is an attempt for it https://github.com/prezi/harfbuzz-js and also is mine also https://github.com/harfbuzz/harfbuzz/pull/743 . You see even https://github.com/emscripten-ports/harfbuzz is empty as the support I've added to emscripten is using just our thing, the only thing remains however having a clean looking js library port, something I'm very interested to do but the trick is do it clean as possible so can merged upstream.

**Comment by ebraminio** [comment] 2019-03-28 12:03
Assigning it to myself to see what happens, maybe we can have the wasm distribution in a repo in github.com/harfbuzz not if in harfbuzz repo itself.

**Comment by ebraminio** [comment] 2019-03-29 23:16
So lets define some goal here, I think as I've put the support in Typr.js https://github.com/photopea/Typr.js/pull/28 already what we can do here eventually to have a cleaned up version of #1636 (just a html or js demo of how to use harfbuzz in browser or nodejs, without build results). We can then decide if we like to put harfbuzz in an npm package or provide .d.ts typescript definition documentation (automated generated) later, or, refer users to Typr.js anyway as a sample use.

**Comment by photopea** [comment] 2019-03-31 17:14
I would be very happy, if we could make some progress in terms of WASM file size.

You are compiling it through a current version of Emscripten, right? The conversion is done through LLVM commands as intermediate state. Is it possible to convert C to WASM directly using other tools, that would provide smaller WASM?

I think my use case would probably the biggest use case of WASM version of HarfBuzz, as there will be hundreds of thousands of people downloading it as a part of the webpage every day :)

**Comment by ebraminio** [comment] 2019-03-31 18:01
I went for building the library without emscripten before, even the fact that may work (but you should provide libc for the library somehow) emscripten itself incorporates good practices from what I can see.

We can reduce the current binary size by compiling harfbuzz without bulitin ucdn and Unicode function, 710kb -> 599kb (zipped, 214kb to 164kb) but that costs in correctness of shaping.

Other things lead to some other reduction, disabling multithread, removing the not used APIs but considering binary size of HarfBuzz on Debian for example https://packages.debian.org/sid/libharfbuzz-bin (800kb which is compressed) I don't believe we can go for less than 150-100kb compressed :)

**Comment by ebraminio** [comment] 2019-03-31 20:00
Applying all the mentioned things, it has become 479.9kb (compressed, 127.0kb) but I'd say 214kb is good also

**Comment by behdad** [comment] 2019-04-01 04:11
Leaving out UCDN is a nonstarter.

As it happens I'm going to work on minimizing HarfBuzz for other uses.  So I'll be working on this.  Would be great to 1. have a streamlined way to build .wasm, and 2. a major user.

My current plans are: 1. better compressor for UCDN and other tables (based on packtab.c in fribidi repo), and 2. easy way to disable periphery API / legacy features (like Arabic fallback shaping).

**Comment by ebraminio** [comment] 2019-04-01 09:50
Classic case of:

![image](https://user-images.githubusercontent.com/833473/55318680-9266b200-5488-11e9-825d-6b4446460a84.png)

from https://hacks.mozilla.org/2018/01/making-webassembly-even-faster-firefoxs-new-streaming-and-tiering-compiler/

> Leaving out UCDN is a nonstarter.

Yes, as said.

> 1. have a streamlined way to build .wasm,

It is using cmake and emscripten #1636 and it is super easy to use and it doesn't make trouble for autotools development.

> 2. a major user.

https://github.com/photopea/Typr.js

Recently there was a huge hype around WASI also https://hacks.mozilla.org/2019/03/standardizing-wasi-a-webassembly-system-interface/

**Comment by photopea** [comment] 2019-04-07 23:28
I would like to thank you for this amazing library, and I am informing you, that it is currently used at www.Photopea.com by thousands of users every day :)

As you open Photopea, 2 MB of data is downloaded (out of this, 250 kB is Harfbuzz, 90 kB are all 104 icons - 160x160px, 60 kB is a [font database](https://www.photopea.com/code/FNTS.js), 130 kB are [localizations in 36 languages](https://www.photopea.com/code/LNG2.js)). Of course, everything is compressed during the transfer.

I wish you could make Harfbuzz smaller, but I don't understand it well enough to be able to give you any advice. I already started a discussion about making the Emscripten JS file smaller: https://github.com/emscripten-core/emscripten/issues/8409

**Comment by behdad** [comment] 2019-04-08 19:22
Oooh, you did integrated it in Photopea already!?  That's amazing!

I'm working on making a mini version of HarfBuzz in https://github.com/harfbuzz/harfbuzz/issues/1652

**Comment by ebraminio** [comment] 2019-04-08 21:44
Reduced from 597222 to 558072 by removing CFF and to 523772 by removing AAT. My changes are on #1636 and only have this set of API `'_hb_version_string', '_malloc', '_hb_blob_create', '_hb_face_create', '_hb_font_create', '_hb_buffer_create', '_hb_buffer_add_utf8', '_hb_buffer_guess_segment_properties', '_hb_buffer_set_direction', '_hb_shape', '_hb_buffer_serialize_glyphs', '_hb_buffer_get_length', '_hb_buffer_serialize_glyphs', '_hb_buffer_destroy', '_hb_font_destroy', '_hb_face_destroy', '_free'` and compressed using closure and seems to work here!
[harfbuzzjs-closure-no-cff-aat.zip](https://github.com/harfbuzz/harfbuzz/files/3056347/harfbuzzjs-closure-no-cff-aat.zip)

**Comment by photopea** [comment] 2019-04-08 21:50
Yes, I did integrate it :) 

I got very excited about minifying Photopea today.

There is a [font database - a large JSON file](https://www.photopea.com/code/FNTS07.js), that Photopea loads every time. There are 4290 fonts. For each font, there are four strings: Family name, Subfamily name, Postscript name, Font URL. Also, a Font Category, and flags with supported scripts. This file was 451 kB and 57 kB ZIPped.  

I made some hacks in my JSON representation (e.g. an empty PostScript name means, that the PostScript name is a concatenation of Family and Subfamily). I turned that JSON [into 135 kB](https://www.photopea.com/code/FNTS.js) and 29 kB ZIPped :)

**Comment by behdad** [comment] 2019-04-08 21:54
Nice!

Want to show us your HarfBuzz integration glue?  I'm afraid you also need a Unicode Bidirectional Algorithm implementation for full correctness.

**Comment by photopea** [comment] 2019-04-08 22:07
I am using the Javascript implementation of BIDI algorithm, that I mentioned at the beginning. I added bidirectional support [about two years ago](https://blog.photopea.com/photopea-2-8-with-more-text-options.html). What glue do you mean?

**Comment by behdad** [comment] 2019-04-08 22:11
Oh right.  Sounds good.

The code calling into HarfBuzz I meant.  Okay, so you probably just missing script-run itemization.

**Comment by behdad** [comment] 2019-04-08 22:11
Ie. mixed-script text will currently be broken.

**Comment by photopea** [comment] 2019-04-08 22:25
@ebraminio Could you give me an example of how to use your latest code? it seems like there is no _hb_blob_destroy .

@behdad  What is a mixed-script? I call HarfBuzz separately on intervals of text, which share the same direction and font (in Photopea, each character can have a different font). I would like to encourage you to go to www.Photopea.com and try it out.

**Comment by brawer** [comment] 2019-04-09 05:35
To render text, every browser already contains a shaping engine; if it was accessible from JavaScript, “download size” would be zero. At some point, there was talk about adding a text shaping API to the JavaScript core libraries, similar to the ICU wrapper in [ECMA-402](http://www.ecma-international.org/ecma-402/1.0/). Does anyone know what happened to that plan? Obviously it’d take a while to bring it through, but browsers have eventually [adopted](https://caniuse.com/#search=intl) the Intl API. (As far as I can see, the main missing piece would be to find someone who can write a good API proposal for ECMA. That person would need to understand text rendering, have good JavaScript fu, and be patient enough to survive the standardization process.)

**Comment by brawer** [comment] 2019-04-09 05:52
Re. mixed-script, there’s a [proposal](https://github.com/tc39/proposals/blob/master/ecma402/README.md) for adding an [Intl.Segmenter](https://github.com/tc39/proposal-intl-segmenter) to JavaScript. But currently, the proposal is only about breaking graphemes, words and sentences (exposing ICU break iterators), not script runs.

**Comment by brawer** [comment] 2019-04-09 06:00
@photopea For correct rendering, you’ll need to do split the input text into script runs before calling HarfBuzz, but it’s [more complicated](https://en.wikipedia.org/wiki/Script_(Unicode)#Special_script_property_values). Perhaps you could follow the logic of [Raqm](https://github.com/HOST-Oman/libraqm); the script itemization code is in [raqm_itemize](https://github.com/HOST-Oman/libraqm/blob/b51b28baac193a7e4fe7d0a77de4a72fc201f0ab/src/raqm.c#L1088).

**Comment by ebraminio** [comment] 2019-04-09 06:13
> it seems like there is no _hb_blob_destroy.

Ah, I've missed adding that call, here is the new version, [harfbuzzjs-closure-no-cff-aat2.zip](https://github.com/harfbuzz/harfbuzz/files/3057396/harfbuzzjs-closure-no-cff-aat2.zip)

**Comment by photopea** [comment] 2019-04-09 08:51
@ebraminio great, thank you! I just updated and it is much smaller indeed :) BTW. is that "harfbuzzjs.js" a direct output from Emscripten, or you minifed it somehow? Do you think there is a space for minifying that JS even further? Could you write a comment on https://github.com/emscripten-core/emscripten/issues/8409 ?

**Comment by ebraminio** [comment] 2019-04-09 16:56
Yes I used closure, you can use Google Closure in rest of your project also :)

**Comment by photopea** [comment] 2019-04-09 18:20
@ebraminio I did use Closure Compiler several years ago, but it turned out to be very slow, so I made my own, which does the same thing, but it is about 50x faster.

But they can make modifications on Emscripten side, that would make the Closure Compiler result even smaller.

**Comment by ebraminio** [comment] 2019-04-09 20:29
> But they can make modifications on Emscripten side

Interesting, I never thought of that!

**Comment by behdad** [comment] 2019-04-09 20:57
> @behdad What is a mixed-script?

Say, you have Hindi and English mixed in the same string.

> I would like to encourage you to go to [www.Photopea.com](http://www.Photopea.com) and try it out.

I did already. :)

**Comment by photopea** [comment] 2019-04-09 21:23
@behdad I understand, that to use GPOS and GSUB tables, you need to know a script, which will lead you to a set of features and lookups, that should be applied to the text. In my library Typr.js, I used to loop through all features and apply all referenced lookups :D (each lookup at most once).

I use PSD format for storing files, which does not store any information about the script. Also, users are not used to enter a script when entering a text. So my goal is to display it like the web browser would display it (you also don't enter the script in HTML, you can only enter the base direction of the paragraph).

**Comment by behdad** [comment] 2019-04-09 21:40
> I use PSD format for storing files, which does not store any information about the script. Also, users are not used to enter a script when entering a text. So my goal is to display it like the web browser would display it (you also don't enter the script in HTML, you can only enter the base direction of the paragraph).

Exactly.  Web browsers as well as any other complete text rendering system internally break the text down into "script runs" automatically and shape each one separately.

**Comment by ebraminio** [comment] 2019-04-09 21:41
Some bug reporting magic will be useful for here I guess,

Steps to reproduce:
1. Create a text holder in Photopea
2. Set FreeSerif font for it
3. Put "ދިسسی" on it

Actual:
![image](https://user-images.githubusercontent.com/833473/55837043-77094000-5b35-11e9-8efc-7505184aa452.png)

Expected:
The thing you see on the browser

![image](https://user-images.githubusercontent.com/833473/55837142-bafc4500-5b35-11e9-9f20-18bf20ee79ea.png)

What happened?
HarfBuzz has determined an incorrect script so rest of the thing went wrong.

Solution:
Segmenting the text by scripts before passing it to HarfBuzz

**Comment by photopea** [comment] 2019-04-09 22:07
I think that currently in practice, people usually use "one script" per layer in Photopea. So this will happen rarely.

I see, that there is Unicode Standard Annex #29. Do you know any implementation, that is not too big? I think the library which performs BIDI algorithm could perform this too, as they both probably need the database of details about Unicode characters (I think that is what you call UCDN).

**Comment by behdad** [comment] 2019-04-09 22:40
No it's not the UAX 29 that you need.  Script itemization is NOT speced at Unicode.  However, here's the easy way to start: just break on any script change.  `hb_unicode_script`.  Then just special-case two values: `HB_SCRIPT_INHERITED` merges with previous character.  `HB_SCRIPT_COMMON` also merges with neighboring.  That's a very good start.

**Comment by behdad** [comment] 2019-04-10 13:46
> To render text, every browser already contains a shaping engine; if it was accessible from JavaScript, “download size” would be zero. At some point, there was talk about adding a text shaping API to the JavaScript core libraries, similar to the ICU wrapper in [ECMA-402](http://www.ecma-international.org/ecma-402/1.0/). Does anyone know what happened to that plan? Obviously it’d take a while to bring it through, but browsers have eventually [adopted](https://caniuse.com/#search=intl) the Intl API. (As far as I can see, the main missing piece would be to find someone who can write a good API proposal for ECMA. That person would need to understand text rendering, have good JavaScript fu, and be patient enough to survive the standardization process.)

Here's one such attempt I did from 2012: http://goo.gl/jAeFRZ

**Comment by photopea** [comment] 2019-04-10 14:33
I am not a big fan of making new web standards for things, that can be done with our own custom code. One may want a whole physics engine to be available through a browser API, or the whole content of the Boost C++ library.

I am very glad, that a modern web browser can be 30 MB big. I don't want it to get e.g. to a size of the .NET environment (4 GB). Not only because billions of people would have to download petabytes of extra data, but also because making a brand new browser would become extremely hard, as makers wouls have problems to keep up with the new standards.

I do understand, that all necessary code is already inside a browser. But making it accessible to JS and making it stupid-proof, catching all unexpected inputs, etc. would make the necessary code 2x larger. And it would only be useful to one in 10 000 websites.

**Comment by behdad** [comment] 2019-04-10 17:11
Imagine if your operating system didn't provide any basic libraries either..  Guess you don't need to imagine, that's what Linux is.  So yeah, if there was a way / repository for different websites to share the same library downloads that could be cached by browsers, then we wouldn't need the browser to provide such services.

But then again, being able to access system fonts is useful.  Unless we also forgo all of that and "system" fonts becomes simply cached online fonts ala Google Fonts and ChromeOS.

**Comment by photopea** [comment] 2019-04-10 17:34
Sharing / caching the same program by multiple websites is not that important in my opinion. E.g. HarfBuzz in WASM is just 150 kB (zipped). Today, people watch 4K videos on Youtube, so loading 150 kB every time you open a website is not a big deal.

Accessing system fonts from a browser will probably never happen. Mainly because people are too scared of fingerprinting (a list of fonts in your OS lets the website know that it is you, no matter if you use Incognito mode, VPN etc.). 

In Photopea, I have 4300 fonts (OTF and TTF files) on the server. These are the only fonts available in Photopea. When a font is needed, it is downloaded over HTTP as a binary file. A font file is parsed and processed by Javascript, so there is no need for any system libraries or system fonts. People can load their own TTF / OTF files manually into Photopea as well. 

I am able to provide the same experience on every OS and device, I am not dependent on system fonts, Google Fonts or ChromeOS.

**Comment by ebraminio** [comment] 2019-04-10 20:48
Here is apparently a proposed Intl.Segmenter polyfill, https://gist.github.com/inexorabletash/8c4d869a584bcaa18514729332300356 not sure if it suffices the need.

**Closed** 2019-04-19 14:51 UTC
Labels: enhancement, question

**Comment by ebraminio** [comment] 2019-04-19 14:53
Finally https://github.com/harfbuzz/harfbuzzjs/
And here is an example of it, https://github.com/harfbuzz/harfbuzzjs/blob/master/examples/hbjs.example.js lets continue the discussion till a release!

**Comment by photopea** [comment] 2019-04-19 16:56
Hey, thanks for creating a separate repository! :)

Note, that I am a person, who does not use native programs during programming, such as C compilers or bash / command line, or npm. I only edit text files with a Notepad. I would be glad, if there was a way I could use Harfbuzz from that repository, but I dont see any JS or WASM file, that is ready to use.

**Comment by ebraminio** [comment] 2019-04-19 19:58
They are available here [harfbuzzjs.zip](https://github.com/harfbuzz/harfbuzz/files/3099139/harfbuzzjs.zip) but will be soon available as a part of harfbuzzjs release on npm also as it is not that cool to put binaries in root of the project. I've also just created a readme file for the project https://github.com/harfbuzz/harfbuzzjs/ let me know if that is clear enough or anything needs to be added.

**Comment by photopea** [comment] 2019-04-23 11:29
Hi, I would like to donate 1000 USD to the HarfBuzz project. It works excellently at Photopea.com and has saved me the struggle of implementing everything myself (even though I already invested hundreds of hours into Typr.js). 

Is there a Donation page? I would like Ebrahim to get the part of it, too, as he helped me a lot. Do you work together in a group?

Also, I am still hoping you manage to make HarfBuzz smaller, either by throwing out unneeded parts, or improving the representation of structures.

**Comment by twardoch** [comment] 2019-04-23 11:52
I'm not sure if there is a donation page, but I think the maintainers will suggest something. HerfBuzz has a long history — started as the FT_Layout submodule of FreeType with simple functionality, then a lot of work was done within Qt, and at some point, years ago, @behdad took over the development, first within RedHat, I think, and then within Google. 

But it never was a “RedHat project” or a “Google project”. Behdad did a massive job and then was joined by others. Firefox, then Chrome, started using it to do the OpenType shaping, and the developers put an incredible amount of work in to make HB result-compatible with Uniscribe, Microsoft’s implementation of OpenType Layout (without having access to sources, so there was a lot of trial-and-error). 

The project has now many man-years of developer work, and the developers have always shown the willingness to implement features (I mean wishes, new functionalities — not the OT features), of course as long as they remained within the scope of the lib. (I once asked for the hb-view tool and proposed its CLI spec, and Behdad did it in a week, which finally made it possible to produce simple text samples in all of the world scripts as PNG, SVG & PDF via Cairo). 

There is a lot of implicit knowledge of Unicode & OpenType encoded in HarfBuzz, or — more broadly speaking — a lot of knowledge about the world typography. Thanks to HarfBuzz, both large and small languages have a chance for accurate and orthographically correct digital text exchange. Together with FreeType and the Google Noto project, HarfBuzz is an immense contribution to the centuries of the human written culture.

**Comment by ebraminio** [comment] 2019-04-24 16:54
Just released the work on npm https://www.npmjs.com/package/harfbuzzjs and the full version on https://wapm.io/package/ebraminio/harfbuzz (apparently a new wasm files package manager) and whole thing, including `.wasm` files and interface file on https://github.com/harfbuzz/harfbuzzjs/releases

> Is there a Donation page?

not aware of any donation page, feel free to send the amount you like to Behdad, otherwise should setup one.

**Comment by photopea** [comment] 2019-04-24 17:07
How do I send money to Behdad? Does he have a bank account in the US or EU?

Thanks for creating all these npm / wasm package manager distribution channels. I do not use them, but I think many will use them. Personally, I would prefer if you invested the effort into Harfbuzz itself, to make it smaller / faster / more robust. Even though it is already quite small and fast for my needs :)

**Comment by ebraminio** [comment] 2019-04-24 17:23
> Personally, I would prefer if you invested the effort into Harfbuzz itself

It is already an squeeze from a 1.9Mb .wasm file (540kb zipped) to 536kb (159kb zipped, your original goal I think) using different techniques we've incorporated but there is of course room for more.

**Comment by behdad** [comment] 2019-04-24 19:41
> How do I send money to Behdad? Does he have a bank account in the US or EU?

I have US accounts, yes.  You can email me@behdad.org.  Thanks for your generous offer!

> Thanks for creating all these npm / wasm package manager distribution channels. I do not use them, but I think many will use them. Personally, I would prefer if you invested the effort into Harfbuzz itself, to make it smaller / faster / more robust. Even though it is already quite small and fast for my needs :)

I'm still working on that in https://github.com/harfbuzz/harfbuzz/issues/1652

For example, I'm shrinking UCDN from over 100kb to about 30kb.  My changes will make it to master soon.

**Comment by photopea** [comment] 2019-05-07 15:59
May I have one more question? Does Harfbuzz support TTC files (Font Collections) ? A Font collection is basically several TTF files concatenated, with a list of offsets to each file at the beginning. They can also share some tables with each other (by sharing offsets to those tables).

When I load a whole TTC file to HarfBuzz, where do I specify, which font should be used for shaping?

**Comment by ebraminio** [comment] 2019-05-07 16:07
Oh it does, you have to put the index you like instead 0 on `module._hb_face_create(blob, 0);`, there is a `hb_face_count` also but not available in your build, you can go without it but let me know if you want it.

**Comment by behdad** [comment] 2019-05-07 16:08
That's the integer index passed to hb_face_create().

**Comment by photopea** [comment] 2019-05-07 16:24
Wow, great, it works perfectly, thanks! :)

**Comment by ebraminio** [comment] 2019-05-12 16:03
New build using Behdad's HB_TINY, only 440kb of .wasm
[harfbuzzjs.zip](https://github.com/harfbuzz/harfbuzz/files/3170283/harfbuzzjs.zip)

**Comment by photopea** [comment] 2019-05-12 21:14
I updated it, works perfectly, thanks! :)

**Comment by ebraminio** [comment] 2019-05-24 10:37
Using new works on HarfBuzz it turned from 440kb to 421kb and after the very recent works Behdad's works it is turned into 371kb, and apprently after enabling `--llvm-lto 1` it has turned to 278kb!

[harfbuzzjs-lto.zip](https://github.com/harfbuzz/harfbuzz/files/3216416/harfbuzzjs-lto.zip)

But apparently I can't make it and the previous version even work here, please make sure if it working there before updating it

**Comment by photopea** [comment] 2019-05-24 13:44
@ebraminio The new size is incredible! However, for me, it returns an empty array of glyphs :(

**Comment by ebraminio** [comment] 2019-05-24 20:30
Now a working version with 2.5.0 release which I can confirm work here also! https://harfbuzz.github.io/harfbuzzjs/ (feel free to pick the wasm from that page even or from below)

[harfbuzzjs.zip](https://github.com/harfbuzz/harfbuzz/files/3218459/harfbuzzjs.zip)

its is only 98kb of zipped wasm, exceeding your goal :)

**Comment by photopea** [comment] 2019-05-24 23:38
I just put it online, works great, thanks! :)

**Comment by ebraminio** [comment] 2019-06-22 21:45
With another round of improvements by Behdad we've reached to 246kb from 280kb and with the removal of hb_serialize, which is necessary for further works, it goes down to 236kb!

[harfbuzzjs.zip](https://github.com/harfbuzz/harfbuzz/files/3317293/harfbuzzjs.zip)

The needed change from your side is to use this instead current serializer, I tested it locally seems to work fine here,
```js
    var length = module._hb_buffer_get_length(buffer);
    var result = [];
    var infosPtr32 = module._hb_buffer_get_glyph_infos(buffer, 0) / 4;
    var positionsPtr32 = module._hb_buffer_get_glyph_positions(buffer, 0) / 4;
    var infos = module.HEAPU32.slice(infosPtr32, infosPtr32 + 5 * length);
    var positions = module.HEAP32.slice(positionsPtr32, positionsPtr32 + 5 * length);
    for (var i = 0; i < length; ++i) {
      result.push({
        g: infos[i * 5 + 0],
        cl: infos[i * 5 + 2],
        ax: positions[i * 5 + 0],
        ay: positions[i * 5 + 1],
        dx: positions[i * 5 + 2],
        dy: positions[i * 5 + 3]
      });
    }
```

This is essential as the next round of works I am working on is about removing emscripten and the glue code (that 10kb js code) which works with a trimmed down libc which now I have a working demo of it here https://harfbuzz.github.io/harfbuzzjs/ng/hb.html

**Comment by photopea** [comment] 2019-06-24 13:45
Hi! Currently, when you open Photopea.com , 1.4 MB is loaded (the whole program). HarfBuzzjs.wasm, which is extra 111 kB (as it is GZIPped), is loaded only if the text tool is used (so we don't load it every time as in the past).

I am alerady quite happy with the progress you have made, and if you plan to keep going, I will wait for the next version :)

I wish all developers cared about the size of their programs at least half as much as you do :)

**Comment by ebraminio** [comment] 2019-06-24 14:16
@photopea, great :) I would say this version worth to be integrated now as the next will have radical changes and we may don't release that soon or ever (as that needs we compile our owned malloc/calloc/realloc/free, which may gets some little time to correctly figured out).

An advantage to the next version is you can compile harfbuzz .wasm by yourself just by downloading llvm installer and it works even in Windows also, current llvm releases http://releases.llvm.org/download.html#8.0.0 which provide an installer for Windows, support compiling and linking wasm32 files. You may like to port some of the other codes you've written for the rest of you app to reduce their size with, it is super easy https://dassur.ma/things/c-to-webassembly/ and doesn't need may complicated setup emscripten and Google Closure have but for now our emscripten builds are only considered stable (even the fact we have the ng builds now working here https://harfbuzz.github.io/harfbuzzjs/ng/hb.html)

So, all the new changes need is to apply this https://github.com/harfbuzz/harfbuzzjs/commit/9fc9e7aa8d83b8602639b590d81e8f8fc77ddc91#diff-291994c3e8f610097e257cfe2a68e019L33 but in your code and use the new module I've uploaded, but please check its validity before publishing it in the production. The next build will mostly need just removing underscores from the calls but this change also and that's why I like to encourage you to apply it now. Thanks

**Comment by ebraminio** [comment] 2019-07-02 08:20
Hey @photopea I've just uploaded the emscripten free version of, a real webassembly distribution of the project with only ~200kb size (78kb gzipped, and without that ~10kb .js wrapper) and here is the demo, https://harfbuzz.github.io/harfbuzzjs/ feel free to copy https://github.com/harfbuzz/harfbuzzjs/blob/master/examples/nohbjs.html but pick the .wasm binary from the demo page! Please note that there are differences between previous emscripten based release and this, our wasm builds have so simple `sbrk` that can't grow their memory based on need so `var exports = result.instance.exports; exports.memory.grow(400); // each page is 64kb in size` is put to create an initial amount of needed RAM. At the end I should note that this not to undermine all the great works happened at emscripten project, their `malloc` is still used in our libc and https://github.com/intel/zephyr/blob/master/lib/libc/minimal/source/string/string.c of Intel Zephyr libc (Apache licensed) is also used, we will review till the release but I guess you will be fine to use our pure .wasm now!

**Comment by kripken** [comment] 2019-07-04 21:23
Is there a side by side comparison of the emscripten and non-emscripten versions (or build instructions for them both)? I'm curious to understand any size difference in the .wasm. How big is that difference?

**Comment by ebraminio** [comment] 2019-07-05 08:59
It is something like 30kb in wasm binary and 10kb in js glue code (both uncompressed), here is how to test,

```bash
$ git clone https://github.com/harfbuzz/harfbuzzjs && cd harfbuzzjs
$ ./build.sh && ls -ltrha hb.wasm # our current pure wasm module
-rwxr-xr-x 1 ebrahim  201K Jul  5 13:06 hb.wasm
$ git checkout 9fc9e7aa8d83b8602639b590d81e8f8fc77ddc91 # last version built with emscripten
$ ./build.sh && ls -ltrha harfbuzzjs.*
-rw-r--r-- 1 ebrahim   11K Jul  5 13:10 harfbuzzjs.js
-rw-r--r-- 1 ebrahim  229K Jul  5 13:10 harfbuzzjs.wasm
```

Downsides:
1. No dynamic memory grow in sbrk https://github.com/harfbuzz/harfbuzzjs/blob/master/libc/main.c#L11
2. Very tight to our use, we don't have STL and have very limited use of libc and tweaked the project to use even less of libc. I've removed printf and friends use specifically for the reason and created a specific libc header https://github.com/harfbuzz/harfbuzzjs/tree/master/libc/include not something every project can afford

Upsides:
1. Full control of module fetch and load. emscripten's is a bit complicated and has its own learning curve.
2. This 40kb save!
3. Maybe works better with wapm and wasm runners outside browser environment.
4. Very easy build tools installation is needed, works in Windows also without Visual Studio installation, only needs clang 8. And it should be much faster.

**Comment by kripken** [comment] 2019-07-05 22:07
Thanks @ebraminio!

Ok, I spent some time building the various options here - mostly I wanted to see if there were any bugs or forgotten flags or optimizations anywhere.

One issue is the emscripten version: using [latest emscripten with the LLVM wasm backend](https://v8.dev/blog/emscripten-llvm-wasm#testing), and using [this modified build.sh](https://gist.github.com/kripken/00cb60f86bbb6f0931ff6e2729a7a178) (I took the new one you had and made it work with emscripten), I get
```shell
$ ls -alh a.*
-rw-rw-r-- 1 alon alon 6.6K Jul  5 14:02 a.out.js
-rw-rw-r-- 1 alon alon 183K Jul  5 14:02 a.out.wasm
```
At 183K that's better than both the emscripten and non-emscripten numbers from before.

But that brings me to the second issue: you can run [Binaryen's wasm-opt tool](https://github.com/WebAssembly/binaryen#wasm-opt) on the non-emscripten wasm (emscripten runs it automatically), and it shrinks it to 178K,
```shell
$ wasm-opt hb.wasm -O -o hb_opt.wasm
$ ls -alh hb.wasm hb_opt.wasm
-rwxrwxr-x 1 alon alon 200K Jul  5 14:12 hb.wasm
-rw-rw-r-- 1 alon alon 178K Jul  5 14:13 hb_opt.wasm
```
And that 178K is the best number of all of them!

Old emscripten was using old LLVM (6). LLVM 8 and 9 (what emcc uses) can do better! Aside from that, running Binaryen typically shrinks wasm backend output by 10-15% percent (on HarfBuzz it's around 11%). With those two issues out of the way, the comparison is more apples to apples, and the difference is the 6K JS and a wasm difference of 5K, which I believe is because of the libc customization here.

Definitely on a project like HarfBuzz, that needs very little runtime support, it's nice to customize your own libc if you have time for that, and such custom runtimes can be smaller than emscripten's general-purpose runtime! The one thing though is you need to make sure to do all the things `emcc` would do for you, like running `wasm-opt`, otherwise the size could be worse, not better.

> No dynamic memory grow in sbrk https://github.com/harfbuzz/harfbuzzjs/blob/master/libc/main.c#L11 I may need your help on this, I mean I don't know how to detect the memory grow is needed.

I think you need to track the current memory size and how close the sbrk limit gets to there. The wasm backend has [intrinsics to help there](https://github.com/llvm/llvm-project/blob/master/clang/include/clang/Basic/BuiltinsWebAssembly.def#L26) (`__builtin_wasm_memory_size, __builtin_wasm_memory_grow`).

 > Correct symbols names in wasm, something I like very much!

I'm not sure what you mean by this? If you build with `emcc --profiling-funcs` for example it will keep symbol names in the wasm, emcc just doesn't emit them by default. (And when [using the wasm backend](https://v8.dev/blog/emscripten-llvm-wasm) the symbol names are also correct in that they don't have any extra `_` prefix.)

**Comment by ebraminio** [comment] 2019-07-06 08:46
Wow, great infromation

> One issue is the emscripten version: using latest emscripten with the LLVM wasm backend, and using this modified build.sh (I took the new one you had and made it work with emscripten), I get

Great, now I think it will be nice provide both binaries in a release, considering how emscripten's is more tested.

> But that brings me to the second issue: you can run Binaryen's wasm-opt tool on the non-emscripten wasm (emscripten runs it automatically), and it shrinks it to 178K,

Great! I wished I could pass 200kb limit, now I have it :)

> Definitely on a project like HarfBuzz, that needs very little runtime support, it's nice to customize your own libc if you have time for that, and such custom runtimes can be smaller than emscripten's general-purpose runtime!

Our own libc is not tested like emscripten's. I will look if I can use rest of the emscripten libc from the source.

> The one thing though is you need to make sure to do all the things emcc would do for you, like running wasm-opt, otherwise the size could be worse, not better.

I tried the one shipped with my distro emscripten and it just shrinked 10k, will try latest one with emsdk once I download it.

> I think you need to track the current memory size and how close the sbrk limit gets to there. The wasm backend has intrinsics to help there (__builtin_wasm_memory_size, __builtin_wasm_memory_grow).

Great help, thanks :)

> I'm not sure what you mean by this? If you build with emcc --profiling-funcs for example it will keep symbol names in the wasm, emcc just doesn't emit them by default. (And when using the wasm backend the symbol names are also correct in that they don't have any extra _ prefix.)

Will use the flag in our emscripten build revival if doesn't impact much the size, I like to have this aournd
![image](https://user-images.githubusercontent.com/833473/60753980-dd481680-9fef-11e9-85b7-86f15c9c49ee.png)
I wish even I could write prototype codes in JS dynamic world then write them in native code if necessary!

Thanks ;)
