### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by FortiterInRe** [harfbuzz/harfbuzz#4272] opened 2023-06-09 13:04 UTC
```
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /home/arch/.cache/yay/harfbuzz-git/src/build
ninja: Entering directory `/home/arch/.cache/yay/harfbuzz-git/src/build'
[122/331] Linking target src/libharfbuzz.so.0.60730.0
FAILED: src/libharfbuzz.so.0.60730.0 
cc  -o src/libharfbuzz.so.0.60730.0 src/libharfbuzz.so.0.60730.0.p/hb-aat-layout.cc.o src/libharfbuzz.so.0.60730.0.p/hb-aat-map.cc.o src/libharfbuzz.so.0.60730.0.p/hb-blob.cc.o src/libharfbuzz.so.0.60730.0.p/hb-buffer-serialize.cc.o src/libharfbuzz.so.0.60730.0.p/hb-buffer-verify.cc.o src/libharfbuzz.so.0.60730.0.p/hb-buffer.cc.o src/libharfbuzz.so.0.60730.0.p/hb-common.cc.o src/libharfbuzz.so.0.60730.0.p/hb-draw.cc.o src/libharfbuzz.so.0.60730.0.p/hb-paint.cc.o src/libharfbuzz.so.0.60730.0.p/hb-paint-extents.cc.o src/libharfbuzz.so.0.60730.0.p/hb-face.cc.o src/libharfbuzz.so.0.60730.0.p/hb-face-builder.cc.o src/libharfbuzz.so.0.60730.0.p/hb-fallback-shape.cc.o src/libharfbuzz.so.0.60730.0.p/hb-font.cc.o src/libharfbuzz.so.0.60730.0.p/hb-map.cc.o src/libharfbuzz.so.0.60730.0.p/hb-number.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-cff1-table.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-cff2-table.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-color.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-face.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-font.cc.o src/libharfbuzz.so.0.60730.0.p/hb-outline.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-layout.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-map.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-math.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-meta.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-metrics.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-name.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-shaper-arabic.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-shaper-default.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-shaper-hangul.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-shaper-hebrew.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-shaper-indic-table.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-shaper-indic.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-shaper-khmer.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-shaper-myanmar.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-shaper-syllabic.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-shaper-thai.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-shaper-use.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-shaper-vowel-constraints.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-shape-fallback.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-shape-normalize.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-shape.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-tag.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ot-var.cc.o src/libharfbuzz.so.0.60730.0.p/hb-set.cc.o src/libharfbuzz.so.0.60730.0.p/hb-shape-plan.cc.o src/libharfbuzz.so.0.60730.0.p/hb-shape.cc.o src/libharfbuzz.so.0.60730.0.p/hb-shaper.cc.o src/libharfbuzz.so.0.60730.0.p/hb-static.cc.o src/libharfbuzz.so.0.60730.0.p/hb-style.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ucd.cc.o src/libharfbuzz.so.0.60730.0.p/hb-unicode.cc.o src/libharfbuzz.so.0.60730.0.p/hb-ft.cc.o src/libharfbuzz.so.0.60730.0.p/hb-glib.cc.o src/libharfbuzz.so.0.60730.0.p/hb-graphite2.cc.o -flto -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libharfbuzz.so.0 -Bsymbolic-functions -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -pthread -lm /usr/lib/libfreetype.so /usr/lib/libglib-2.0.so /usr/lib/libgraphite2.so -Wl,--end-group
/usr/bin/ld: /tmp/cc68p5ek.ltrans0.ltrans.o:(.data.rel.local.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
```

**Comment by FortiterInRe** [comment] 2023-06-09 13:05
[135/331] Compiling C++ object src/libh...zz-subset.so.0.60730.0.p/hb-subset.cc.o
ninja: build stopped: subcommand failed.

**Comment by behdad** [comment] 2023-06-10 14:44
Is this using meson on Linux?

**Comment by khaledhosny** [comment] 2023-06-11 22:10
Duplicate of #3163

**Closed by khaledhosny** 2023-06-11 22:10 UTC
