### ISSUE TITLE
different behavior of hb_ft_font_set_funcs vs hb_ot_font_set_funcs in vertical, one of them is broken

### ISSUE THREAD

**Issue by HinTak** [harfbuzz/harfbuzz#1248] opened 2018-10-14 23:38 UTC
288 vs 216 is a lot of difference - one of them is broken (actually I know which one...):

```
hb-view --font-funcs=ft --direction=ttb  -o a.png -O png  msmincho.ttc   '《日本ょ》'
$ file a.png
a.png: PNG image data, 288 x 1312, 8-bit grayscale, non-interlaced
```

```
$ hb-view --font-funcs=ot --direction=ttb  -o a.png -O png  msmincho.ttc   '《日本ょ》'
$ file a.png
a.png: PNG image data, 216 x 1312, 8-bit grayscale, non-interlaced
```

**Comment by khaledhosny** [comment] 2018-10-15 00:00
Duplicate of https://github.com/harfbuzz/harfbuzz/issues/537.

**Comment by khaledhosny** [comment] 2018-10-15 08:35
Reopening per https://github.com/harfbuzz/harfbuzz/issues/537#issuecomment-429753664

**Comment by behdad** [comment] 2018-10-20 23:30
> ascender/descender/line_gap= 220 36 0 h ascender/descender/line_gap= 220 -36 0 v ascender/descender/line_gap= 220 36 0

What are these printouts of?

**Comment by behdad** [comment] 2018-10-20 23:41
So, msmincho has descent -36 in hhea table and +36 in vhea table.  That's what HB is returning.  One can argue that the way vhea descent is written is consistent with it needing a negation...  FreeType doesn't seem to use that value whatsoever.

I like to see the values in a few other fonts before doing anything here.

**Comment by behdad** [comment] 2018-10-20 23:42
NotoSansCJK-Regular has, in hhea:
```
    <ascent value="880"/> 
    <descent value="-120"/> 
    <lineGap value="500"/> 
```

and vhea:
```
    <ascent value="500"/> 
    <descent value="-500"/> 
    <lineGap value="500"/> 
```

This is consistent with what I would have expected.

@kenlunde have you seen the issue in previous comment in many fonts?

**Comment by kenlunde** [comment] 2018-10-21 10:37
@behdad You're looking at a Version 1.000 font, because that particular font (with "CJK" in the name, but without any two-letter lowercase region identifier after it) went away in Version 1.001 and beyond. The Version 1.000 font also has those values. The 'hhea' and 'vhea' values of the current version (1.004) are as follows:

`<ascent value="1160"/>
<descent value="-320"/>
<lineGap value="0"/>`

`<ascent value="500"/>
<descent value="-500"/>
<lineGap value="0"/>`

And yes, the 'vhea' table values in those Microsoft fonts are odd indeed. The values that we're setting in the _Source Han_ and _Noto CJK_ fonts are based on current best practices.

**Comment by HinTak** [comment] 2018-10-21 14:31
That's unfortunate. Microsoft windows has a majority market share. Japanese is the most common language one might do vertical layout. msmincho is one of the most commonly available japanese fonts. Thus this is one of the most common use cases.

**Comment by behdad** [comment] 2018-10-21 21:49
> Microsoft windows has a majority market share. Japanese is the most common language one might do vertical layout. msmincho is one of the most commonly available japanese fonts. Thus this is one of the most common use cases.

You are repeating yourself.

**Comment by kenlunde** [comment] 2018-10-21 22:16
Keep in mind that Microsoft is also notorious for hard-wiring various values elsewhere in their ecosystem, thus rendering the actual values in the fonts void. It's only when other font consumers start to deal with such fonts do issues arise. I can't say for certain that this is the case for these particular fonts, because I cannot see what is under the proverbial hood, which is referring to Windows OS, not the fonts.

**Closed** 2018-10-24 00:01 UTC
Labels: Vertical

**Comment by stbergmann** [comment] 2018-11-14 14:54
With

> descender = -abs (os2_table->sTypoDescender);

in 401cdf07922f66c762dabfd8e3d45c35e33de7c0 showing that `OT::hmtxvmtx::accelerator_t::descender` is intended to contain negative values, any reason why it is declared as

> unsigned short descender;

(in the same file)?

(Asking because with Clang's new `-fsanitize=implicit-signed-integer-truncation` that warns at runtime about suspicious integer truncations, I'm seeing such a warning in one of LibreOffice's tests, and try to understand what's going on.  LibreOffice is still using HarfBuzz 1.8.4, and things may have changed upstream meanwhile.  Nevertheless, that odd signed/unsigned mismatch looked like a good starting point.)

**Comment by behdad** [comment] 2018-11-14 14:57
> > 
> 
> in [401cdf0](https://github.com/harfbuzz/harfbuzz/commit/401cdf07922f66c762dabfd8e3d45c35e33de7c0) showing that `OT::hmtxvmtx::accelerator_t::descender` is intended to contain negative values, any reason why it is declared as
> 
> > unsigned short descender;
> 
> (in the same file)?

Fixed.  In the future please file a new issue.
