### ISSUE TITLE
[AAT] Kannada MN shaping discrepancies (CoreText vs OT)

### ISSUE THREAD

**Issue by jfkthame** [harfbuzz/harfbuzz#1530] opened 2019-01-02 23:16 UTC
Using Kannada MN.ttc from macOS 10.13.6, shaping doesn't agree for this sequence:

```
$ hb-shape --font-file "Kannada MN.ttc" --unicodes C9C,CCD,C9E,CBE --shaper coretext
[kn_jnya.nohook=0+1464|kn_matra_aa.comb=2+840]

$ hb-shape --font-file "Kannada MN.ttc" --unicodes C9C,CCD,C9E,CBE --shaper ot
[kn_ja.nohook=0+1464|kn_matra_aa.comb=0+840|kn_nya.vattu=0+339]
```

And couple more examples:
```
$ hb-shape --font-file "Kannada MN.ttc" --unicodes CB8,CCD,C9F,CCD,200C,CB8 --shaper coretext
[kn_sa.virama=0+1914|kn_tta.virama=2+2151|kn_sa=5+1257]

$ hb-shape --font-file "Kannada MN.ttc" --unicodes CB8,CCD,C9F,CCD,200C,CB8 --shaper ot
[kn_sa.virama=0+1914|kn_tta.vattu=0@-500,0+0|space=4+0|kn_sa=5+1257]
```

```
$ hb-shape --font-file "Kannada MN.ttc" --unicodes C95,CCD,CB7,CC7 --shaper coretext
[kn_kssa.e=0+1365|_blank=2+0|kn_length_mark=2+696]

$ hb-shape --font-file "Kannada MN.ttc" --unicodes C95,CCD,CB7,CC7 --shaper ot
[kn_ka.e=0+1030|kn_ssa.vattu=0+319|kn_length_mark=0+696]
```

**Comment by behdad** [comment] 2019-01-24 11:44
Same here.  We are running GSUB, not morx, because the os2.achVendID is "UNKN", NOT "MUTF". :(

**Comment by behdad** [comment] 2019-12-05 11:08
Closing as duplicate of https://github.com/harfbuzz/harfbuzz/issues/1529

**Closed by behdad** 2019-12-05 11:08 UTC
Labels: aat
