### ISSUE TITLE
Positioning of combining marks encoded in the PUA

### ISSUE THREAD

**Issue by psb1558** [harfbuzz/harfbuzz#2401] opened 2020-05-12 16:56 UTC
In LibreOffice, Firefox and Chrome, anchors are disregarded for combining marks when they have codepoints in the PUA, e.g.
<img width="50" alt="image" src="https://user-images.githubusercontent.com/16215767/81721741-599c5900-944e-11ea-9794-98c3f5d2aea7.png">
However, hb-view shows the same correctly rendered:
<img width="76" alt="image" src="https://user-images.githubusercontent.com/16215767/81721976-b566e200-944e-11ea-90fa-d17985b94a65.png">
My font, [JuniusX](https://github.com/psb1558/Junicode-New), appears to have these marks correctly classified, etc. The Medieval Unicode Font Initiative prescribes a good many combining marks with PUA encodings for compliant fonts (so this is likely to be an issue for other fonts). So my questions are:

- Could these applications be deliberately disabling anchor positioning for non-Unicode marks? Or
- Could they be somehow triggering a bug in Harfbuzz that is not triggered when I use hb-view?
- Would it be best to provide unencoded equivalents of these combining marks with access via OT features?

BTW, InDesign renders these marks correctly, but MS Word for Mac does not.

**Comment by khaledhosny** [comment] 2020-05-12 17:11
Most likely it is a script itemization issue. PUA code points don’t have an assigned script, so it is possiple that these applications are putting them in their own script run, which will break shaping since HarfBuzz only sees a single run at a time.

`hb-view` will work because it doesn’t do any itemization, it will use the script of the first valid script that is now _Common_ or _Inherited_ for all the text. 

Unicode script itemization is under-specified and each application/library have its own slightly different algorithm. It is not even obvious to me what is the right fix here, as script itemization happens at character-level and does not consult any font properties, and I’m not sure of characters with _Unknown_ script should be handled as _Common_ or something else.

I’m afraid you will have to report the issue to each individual project and hope for it to be fixed.

**Comment by khaledhosny** [comment] 2020-05-12 17:12
I think @behdad was recently suggestion that HarfBuzz provide an API for script itemization, so that would be something to consider if we do that. Applications will still need to use that yet to be written API.

**Comment by khaledhosny** [comment] 2020-05-12 17:15
Alternate glyphs for existing combining marks should work, so that is a possible work around. PUA does not really lend itself well to advanced OpenType layout.

**Comment by jfkthame** [comment] 2020-05-12 17:24
Yes, as Khaled says, this is almost certainly due to script itemization separating the PUA mark from the Latin base letter, so they end up being shaped independently.

Perhaps it would be reasonable for script-run itemizers to allow "unknown" characters to be absorbed into the current script run, like "inherited" and "common"; that ought to work for most use cases, at least, and seems like it'd be just as reasonable a guess for shaping behavior as any other.

Seems like the main thing the Medieval Unicode Font Initiative ought to be doing, though, is ensuring that all needed marks are adequately encoded in Unicode. Using the PUA will always come with limitations and problems.

**Comment by jfkthame** [comment] 2020-05-12 17:33
OK, I can confirm that modifying the script itemizer in Firefox to allow Script=Unknown characters to be merged into the surrounding run does fix the issue here and allows the diacritic to be positioned as expected.

Whether that's a change we can actually make without any other ill effects may need a bit more investigation; I'd suggest [filing a bug](https://bugzilla.mozilla.org/) if you'd like us to explore the possibility further.

**Comment by psb1558** [comment] 2020-05-12 17:46
Thanks for all these admirably clear and interesting comments! You've given me a good bit of clarity about this issue.

Over the years, MUFI has gotten a number of combining marks (and other things) encoded in Unicode, others not (I'm not sure why). I understand the point about the limitations of the PUA, and as I am ambivalent about using it for a purpose like this at all (and doubtful that what you're describing is actually a bug), I'm not minded to push this by filing bugs with the various apps using HB. Instead I think I'll experiment with different workarounds at the font level.

**Comment by khaledhosny** [comment] 2020-05-13 14:49
I guess we can close this issue then.

**Closed by khaledhosny** 2020-05-13 14:49 UTC
Labels: question
