### ISSUE TITLE
Sinhala rendering issue on Fedora 37

### ISSUE THREAD

**Issue by pnemade** [harfbuzz/harfbuzz#3835] opened 2022-09-30 10:24 UTC
We received Sinhala rendering bug https://bugzilla.redhat.com/show_bug.cgi?id=2129619 and after some analysis we concluded harfbuzz rendering is the problem. I keep downgraded harfbuzz-5.2.0 till harfbuzz-4.3.0 and found the last working release is harfbuzz-4.3.0. The next non-working build we have in Fedora 37 is harfbuzz-4.4.0

How to reproduce this issue.
1) Add input method si-wijesekara.mim on Fedora 37
2) Try to input these 2 keys` f + l `

working rendering with harfbuzz-4.3.0 on Fedora 37 is
![image](https://user-images.githubusercontent.com/671366/193249809-4a59de64-4d90-441e-a4e5-dfd262945b8c.png)

Incorrect rendering with harfbuzz-4.4.0 or later on Fedora 37 is
![image](https://user-images.githubusercontent.com/671366/193249925-c1c785f4-9b74-44c6-bb23-bbedbdce47a9.png)

**Comment by pnemade** [comment] 2022-09-30 10:38
It appears this rendering issue appeared after Sinhala rendering moved to use the USE shaper instead of “indic” one.

**Comment by khaledhosny** [comment] 2022-09-30 10:44
Duplicate of #3725

**Closed by khaledhosny** 2022-09-30 10:44 UTC

**Comment by pnemade** [comment] 2022-09-30 10:51
Thanks!
