### ISSUE TITLE
See BLFS "FreeType-2.11.0 (after HarfBuzz-3.1.2 is installed, reinstall FreeType-2.11.0)"

### ISSUE THREAD

**Issue by rubyFeedback** [harfbuzz/harfbuzz#3317] opened 2021-12-02 08:23 UTC
Hi there,

See:

https://www.linuxfromscratch.org/blfs/view/svn/general/harfbuzz.html

"and FreeType-2.11.0 (after HarfBuzz-3.1.2 is installed, reinstall FreeType-2.11.0)"

I am having increasingly difficult problems getting this to work largely due to 
hb-ft.h not being available when I thought it would be. This is not solely
the fault of harfbuzz alone, mind you, but mixing different versions of
the stack.

But, I also noticed that when we compile harfbuzz, we may end up not
having hb-ft.h due to freetype/fontconfig not having been there or
something. Could this situation be simplified? For instance, would it
be possible to perhaps install a hb-ft.h dummy or something, at the
least for backwards stable versions of freetype/fontconfig? I would not
even make this issue request if the BLFS instructions would have
worked for me, but for whatever the reasons they don't work for me
right now and it is so frustrating to try to find out where the error
happens. The whole "install a, then install b, then install a" again is,
IMO, an indicator that something in the build up logic does not work.
We normally should never need this; in oldschool GNU configure
days we can do so via --flags. I don't know what the modern
cmake/meson equivalents are, and even the LFS/BLFS guys struggle
since they recommend this circular build up compilation thing, which
is sooooooo strange ...

**Comment by khaledhosny** [comment] 2021-12-05 19:21
Duplicate of 2377

**Comment by khaledhosny** [comment] 2021-12-05 19:22
Duplicate of #2377

**Closed by khaledhosny** 2021-12-05 19:21 UTC
