### ISSUE TITLE
Ci build tests on MSYS2 encountering timeouts

### ISSUE THREAD

**Issue by alerque** [harfbuzz/harfbuzz#2697] opened 2020-09-29 14:02 UTC
As a follow up to #2689, the CI job for MSYS2 is encountering timeout errors and hence not very useful. These should be tracked down and resolved somehow

**Comment by alerque** [comment] 2020-09-29 14:57
PR #2698 seems to be an exploration into this issue.

**Comment by dscorbett** [comment] 2020-09-29 17:07
I ran [a job](https://github.com/harfbuzz/harfbuzz/runs/1183305610) based on 45de128930a902004baa875831e38ef62780ae2e with the GitHub actions pared down to just the MINGW32 test. The test timed out, whereas in the base commit, it did not time out. I conclude that the problem is caused by a change outside this repository.

**Comment by khaledhosny** [comment] 2020-10-04 06:47
This seems to have fixed itself, confirming it was an external issue.

**Comment by alerque** [comment] 2020-10-04 07:11
Humbug. On the one hand it's nice to see green checkmarks all the way down. On the other hand it's somewhat uncomfortable not knowing what was actually wrong. It does smell like an external problem though. The individual tests that were timing out before didn't just stop hitting the 30s timeout, they started succeeding in the normal expected < 0.1s range, roughly matching relative times of tests on other platforms.

**Comment by khaledhosny** [comment] 2020-10-07 19:01
Grrr, it is failing again. This is really annoying and very unhelpful!

**Comment by khaledhosny** [comment] 2020-10-14 21:03
This is reproducible locally with msys2, and seems to be related to `G_SLICE=always-malloc` in the test environment, dropping it fixes the timeout.

Looks like a GLib bug, but I’m not also sure why we need to set this.

**Comment by behdad** [comment] 2020-10-14 21:11
> This is reproducible locally with msys2, and seems to be related to `G_SLICE=always-malloc` in the test environment, dropping it fixes the timeout.
> 
> Looks like a GLib bug, but I’m not also sure why we need to set this.

That seems really suspicious indeed...
We don't *need* to set this. Just makes leak-tracking under valgrind and possibly other systems more useful.

**Comment by khaledhosny** [comment] 2020-10-14 21:12
It seems that setting `G_SLICE` env variable to any non-empty value will cause the test to just freeze.

**Comment by behdad** [comment] 2020-10-14 21:20
> It seems that setting `G_SLICE` env variable to any non-empty value will cause the test to just freeze.

Can that be narrowed down to a glib issue without harfbuzz code whatsoever?

**Comment by khaledhosny** [comment] 2020-10-14 21:45
> Can that be narrowed down to a glib issue without harfbuzz code whatsoever?

Yes. This reproduces the freeze as well:
```C
#include <glib.h>
int main(int argc, char** argv) {
  g_print("Test");
}
```

**Comment by khaledhosny** [comment] 2020-10-14 22:03
https://github.com/msys2/MINGW-packages/issues/7118

**Comment by behdad** [comment] 2020-10-14 22:05
Wow. Thanks.

**Comment by khaledhosny** [comment] 2020-10-17 15:47
This is fixed now.

**Closed by khaledhosny** 2020-10-17 15:47 UTC
