### ISSUE TITLE
harfbuzz 5.0.0 and higher breaks terminus font

### ISSUE THREAD

**Issue by nvidiaLinuxUser** [harfbuzz/harfbuzz#3755] opened 2022-07-25 13:20 UTC
On Arch Linux and other distros, upgrading to harfbuzz 5.0.0 or higher (in testing repository on arch) breaks the [terminus font](https://archlinux.org/packages/community/any/terminus-font/) (otb version) in [foot terminal](https://archlinux.org/packages/community/x86_64/foot/).

![](https://user-images.githubusercontent.com/105428527/180790526-a9021081-b0cb-40df-a4cf-98c5be583a72.png)
*Before*

![](https://user-images.githubusercontent.com/105428527/180791021-ecd690e7-4d33-4d51-89e9-c5114735d47c.png)
*After*

**Comment by khaledhosny** [comment] 2022-07-25 13:57
This seems to be using hb-ft, so possibly a duplicate of #3754.

**Comment by behdad** [comment] 2022-07-25 14:41
Fixed. We'll get a release out.

**Closed** 2022-07-25 14:40 UTC
