### ISSUE TITLE
Upgrade to v5 broke font spacing

### ISSUE THREAD

**Issue by ETNyx** [harfbuzz/harfbuzz#3767] opened 2022-07-31 10:32 UTC
Hello,

after upgrade to v5 it start to occurring weird spacing problem whit some fonts (all bitmap font, specifically Terminus font). All chars are overlapping on first position all over self (please see attached screenshot). So far I fixed it by downgrading to v4 (harfbuzz-4.4.1-1 and harfbuzz-icu-4.4.1-1).

OS: Archlinux (https://archlinux.org/)
Affected version: 5.0.1-1 (https://archlinux.org/packages/extra/x86_64/harfbuzz/)
Font: Terminus (https://archlinux.org/packages/community/any/terminus-font/)
Terminal: Terminology (https://archlinux.org/packages/community/x86_64/terminology/)

![Screenshot from 2022-07-31 11-54-05](https://user-images.githubusercontent.com/2624462/182021349-7dc0eb83-214b-4836-b36b-d76074fdd1ec.png)
)

**Comment by khaledhosny** [comment] 2022-07-31 10:40
Duplicate of #3755

**Closed by khaledhosny** 2022-07-31 10:40 UTC

**Comment by ETNyx** [comment] 2022-07-31 10:51
Ahh sorry didn't saw it :-)
