### ISSUE TITLE
[hb-view] Doesn't understand linked axes

### ISSUE THREAD

**Issue by ctrlcctrlv** [harfbuzz/harfbuzz#2743] opened 2020-11-13 11:18 UTC
It is a recognized font creation trick that if you make multiple axes with the same tag in the fvar and STAT tables, and mark all but one hidden, that changing the value of one changes the value of all. _Cf._ https://twitter.com/jmsoleb/status/1325735951730155521

`hb-view`, however, acts as if only one axis was set to the chosen value.

```bash
for i in `seq -f "%04g" 0 10 1000`; do hb-view --variations="0001=$i" NLI_unmangled.ttf -o $i.png --text-file=../gif-text.txt; echo $i; done
```

Therefore I am for now producing "mangled" and "unmangled" versions of my FontForge NLI/HOI example. See https://github.com/ctrlcctrlv/FontForge-Higher-Order-Interpolation

**Comment by behdad** [comment] 2020-11-17 01:16
Problem code is in `hb_font_set_variations()`. Isn't too hard to fix.

**Comment by behdad** [comment] 2020-11-18 10:46
Duplicate of https://github.com/harfbuzz/harfbuzz/issues/1673

**Closed by behdad** 2020-11-18 10:46 UTC
