### ISSUE TITLE
BUILD: src/relative_to.py fails to execute if python3 is not located in /usr/bin

### ISSUE THREAD

**Issue by debohman** [harfbuzz/harfbuzz#4458] opened 2023-10-23 00:09 UTC
This results in a failure during the meson configuration. This is not portable to environments where `python3` is located elsewhere. Something like the following is needed:

```
--- a/src/relative_to.py
+++ b/src/relative_to.py
@@ -1,4 +1,4 @@
-#!/usr/bin/python3
+#! /usr/bin/env python3
 
 import sys
 from os import path
```

**Comment by khaledhosny** [comment] 2023-10-23 04:35
Duplicate of #4450

**Closed by khaledhosny** 2023-10-23 04:35 UTC
