### ISSUE TITLE
More instancer-solver fixes to port from fonttools

### ISSUE THREAD

**Issue by anthrotype** [harfbuzz/harfbuzz#4319] opened 2023-07-11 09:51 UTC
heads up https://github.com/fonttools/fonttools/pull/3179 /cc @qxliu76 @garretrieger

**Comment by behdad** [comment] 2023-07-11 14:47
Thanks Cosimo. Duplicate of https://github.com/harfbuzz/harfbuzz/issues/4290

**Closed** 2023-07-11 15:08 UTC
