### ISSUE TITLE
missing line in simple shaping example?

### ISSUE THREAD

**Issue by mbutterick** [harfbuzz/harfbuzz#1424] opened 2018-11-28 20:49 UTC
The sample code in the simple shaping example includes this chunk:

```c
#include <hb-ft.h>
FT_New_Face(ft_library, font_path, index, &face)
hb_font_t *font = hb_ft_font_create(face);
```

When I tried the example, the shaping worked (got the right glyph indexes) but the positioning did not (got all zeroes in each positioning record). 

In the [FreeType docs](https://www.freetype.org/freetype2/docs/tutorial/step1.html) I learned that:

> When the FT_New_Face function is called (or one of its siblings), it automatically creates a new size object for the returned face … When a new face object is created, **all elements are set to 0** during initialization. To populate the structure with sensible values, you should call FT_Set_Char_Size.

Thus, to make the simple shaping example work, I had to add:

```c
FT_Set_Char_Size(face, 0, 1000, 0, 0);
```

After this, I got position values that made sense.

**Comment by khaledhosny** [comment] 2018-11-28 21:31
Duplicate of #298, cc @n8willis.

**Closed by khaledhosny** 2018-11-28 21:31 UTC
Labels: documentation, duplicate
