### ISSUE TITLE
[AAT] Mapping of multiple feature requests to AAT is broken

### ISSUE THREAD

**Issue by jfkthame** [harfbuzz/harfbuzz#2305] opened 2020-04-03 13:55 UTC
First, let's check default shaping of Apple Chancery:
```
$ hb-shape --font-file /System/Library/Fonts/Supplemental/Apple\ Chancery.ttf --font-funcs ot "first"
[f_i=0+1097|r=2+853|s=3+728|t=4+725]
```

Passing `dlig=1` will enable an additional (discretionary) ligature for "st":
```
$ hb-shape --font-file /System/Library/Fonts/Supplemental/Apple\ Chancery.ttf --font-funcs ot --features dlig=1 "first"
[f_i=0+1097|r=2+853|s_t=3+1438]
```

And passing `liga=0` will disable the (default-enabled) "fi" ligature:
```
$ hb-shape --font-file /System/Library/Fonts/Supplemental/Apple\ Chancery.ttf --font-funcs ot --features liga=0 "first"
[f=0+639|i=1+606|r=2+853|s=3+728|t=4+725]
```

So far, so good.

However, if we pass some additional feature requests (completely unrelated to the ligature type), the ligature controls no longer work:
```
$ hb-shape --font-file /System/Library/Fonts/Supplemental/Apple\ Chancery.ttf --font-funcs ot --features dlig=1,sups=0,tnum=0 "first"
[f_i=0+1097|r=2+853|s=3+728|t=4+725]

$ hb-shape --font-file /System/Library/Fonts/Supplemental/Apple\ Chancery.ttf --font-funcs ot --features liga=0,sups=0,tnum=0 "first"
[f_i=0+1097|r=2+853|s=3+728|t=4+725]
```

Some debugging indicates that this is because the call to `map->features.bsearch (type)` in `Chain::compile_flags` fails to find the expected entry in the given map. (Note that changing `bsearch` to `lsearch` there makes it work correctly.)

It seems the sense of the comparison in `int cmp (hb_aat_layout_feature_type_t ty) const` method in `hb_aat_map_builder_t::feature_info_t` is reversed, which makes the `bsearch` fail except in the trivial case where the initial (middle) element it looks at matches the target -- which is why the degenerate case of a single feature request works.

Reversing the comparison in this `cmp` method fixes the behavior.

**Comment by drott** [comment] 2020-04-03 14:27
a) Possible duplicate of https://github.com/harfbuzz/harfbuzz/issues/2123?

a) Is this issue also the reason why for example small caps are broken with "Apple Chancery" after the Tibetan fix (b1c0b9da2ff105d3476fed411e1d7010decb394e)?

After b1c0b9da2ff1:

```util/hb-view "/Library/Fonts/Apple Chancery.ttf" --features="smcp" "Chancery"```

![chancery_no_smcp](https://user-images.githubusercontent.com/1021784/78371195-4b962580-75d0-11ea-9d90-31bec5c840a9.png)

Before:

![chancery_smcp](https://user-images.githubusercontent.com/1021784/78371225-5781e780-75d0-11ea-9243-40eb029f2080.png)

**Comment by drott** [comment] 2020-04-03 14:30
b) still fails after 598d5c0 - I'll file a separate issue.

**Comment by drott** [comment] 2020-04-03 14:32
b) filed as #2307

**Closed** 2020-04-03 14:50 UTC
