### ISSUE TITLE
segfault in libharfbuzz.so

### ISSUE THREAD

**Issue by sciamano** [harfbuzz/harfbuzz#3337] opened 2021-12-16 21:15 UTC
I'm observing reproducible crashes of `mate-terminal` under Linux (Debian in my case). After the crash `dmesg` reports segfaults in `libharfbuzz.so` like
`[ 1724.970454] mate-terminal[10512]: segfault at 7efd1511de2b ip 00007efd0f44000d sp 00007ffc92e2ea50 error 4 in libharfbuzz.so.0.20704.0[7efd0f3e9000+a5000]`

To reproduce it, download two version of a font, e.g. JetBrainsMono v2.225 and 2.242 (but I also see the crash for other fonts, so it is not a font-specific issue).

Steps:
1. copy older version (2.225 ) of  `JetBrainsMono-Regular.ttf` to `~/.local/share/fonts`
2. configure `mate-terminal` to use the JetBrainsMono font
3. start one or multiple `mate-terminal`s and keep them running
4. inside a `screen` session or from a text console: overwrite the `JetBrainsMono-Regular.ttf` with the file from the newer version (2.242)
5. in a running `mate-terminal`, run `dd if=/dev/random count=4` and all terminals will disappear 

Without manipulations (i.e. overwriting) with the font files, I can run `dd if=/dev/random count=4` or even `cat /dev/random` without any issues.

**Comment by khaledhosny** [comment] 2021-12-16 21:39
Duplicate of #3114

**Closed by khaledhosny** 2021-12-16 21:39 UTC
