### ISSUE TITLE
High Sierra brew install fail

### ISSUE THREAD

**Issue by mingxin-yang** [harfbuzz/harfbuzz#4321] opened 2023-07-12 07:26 UTC
macOS 10.13

```
==> Fetching harfbuzz
==> Downloading https://github.com/harfbuzz/harfbuzz/raw/fc0daafab0336b847ac14682e581a8838f36a0bf/test/shapi
Already downloaded: /Users/fourmol/Library/Caches/Homebrew/downloads/b0f20064588dc70dd5c74e36b842326d9dbbeacab35c63c3d900a8b34aaba98f--270b89df543a7e48e206a2d830c0e10e5265c630.ttf
==> Downloading https://github.com/harfbuzz/harfbuzz/archive/7.1.0.tar.gz
Already downloaded: /Users/fourmol/Library/Caches/Homebrew/downloads/9b161baf8fe9853a3d6c74e5b1daa560d1937f2c31f28d8da957d3b2db947c90--harfbuzz-7.1.0.tar.gz
==> Upgrading harfbuzz
  2.6.2 -> 7.1.0 

==> meson setup build --prefix=/usr/local/Cellar/harfbuzz/7.1.0 --libdir=/usr/local/Cellar/harfbuzz/7.1.0/li
==> meson compile -C build --verbose
Last 15 lines from /Users/fourmol/Library/Logs/Homebrew/harfbuzz/02.meson:
    + keys_ref ()
    ^ ~~~~~~~~~~~
../src/hb-meta.hh:76:41: note: expanded from macro 'HB_AUTO_RETURN'
#define HB_AUTO_RETURN(E) -> decltype ((E)) { return (E); }
                                        ^
../src/hb-ot-post-table-v2subset.hh:81:44: note: in instantiation of template class 'hb_hashmap_t<hb_array_t<const char>, unsigned int, true>' requested here
  hb_hashmap_t<hb_bytes_t, uint32_t, true> glyph_name_to_new_index;
                                           ^
3 errors generated.
[100/108] clang++ -Iutil/hb-ot-shape-closure.p -Iutil -I../util -I. -I.. -Isrc -I../src -I/usr/local/opt/libpng/include/libpng16 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/libffi/3.4.4/include -I/usr/local/Cellar/fontconfig/2.14.2/include -I/usr/local/Cellar/pcre2/10.42/include -I/usr/local/Cellar/glib/2.76.0/include -I/usr/local/Cellar/glib/2.76.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.76.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libxau/1.0.11/include -I/usr/local/Cellar/libxdmcp/1.1.4/include -I/usr/local/Cellar/libxcb/1.15_1/include -I/usr/local/Cellar/libx11/1.8.4/include -I/usr/local/Cellar/libxext/1.3.5/include -I/usr/local/Cellar/libxrender/0.9.11/include -I/usr/local/Cellar/pixman/0.42.2/include/pixman-1 -I/usr/local/Cellar/cairo/1.16.0_5/include/cairo -I/usr/local/Cellar/xorgproto/2022.2/include -fcolor-diagnostics -Wall -Winvalid-pch -std=c++11 -fno-exceptions -fno-rtti -O3 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -DHAVE_CONFIG_H -Wno-non-virtual-dtor -MD -MQ util/hb-ot-shape-closure.p/hb-ot-shape-closure.cc.o -MF util/hb-ot-shape-closure.p/hb-ot-shape-closure.cc.o.d -o util/hb-ot-shape-closure.p/hb-ot-shape-closure.cc.o -c ../util/hb-ot-shape-closure.cc
[101/108] env PKG_CONFIG_PATH=/usr/local/opt/gobject-introspection/lib/pkgconfig:/usr/local/opt/python@3.11/lib/pkgconfig:/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/pcre2/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/glib/lib/pkgconfig:/usr/local/opt/libxau/lib/pkgconfig:/usr/local/opt/libxdmcp/lib/pkgconfig:/usr/local/opt/libxcb/lib/pkgconfig:/usr/local/opt/libx11/lib/pkgconfig:/usr/local/opt/libxext/lib/pkgconfig:/usr/local/opt/libxrender/lib/pkgconfig:/usr/local/opt/lzo/lib/pkgconfig:/usr/local/opt/pixman/lib/pkgconfig:/usr/local/opt/cairo/lib/pkgconfig:/usr/local/opt/graphite2/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/xorgproto/share/pkgconfig:/private/tmp/harfbuzz-20230712-59949-4yuwuj/harfbuzz-7.1.0/build/meson-uninstalled /usr/local/Cellar/gobject-introspection/1.76.0/bin/g-ir-scanner --quiet --no-libtool --namespace=HarfBuzz --nsversion=0.0 --warn-all --output src/HarfBuzz-0.0.gir --c-include=hb-gobject.h --cflags-begin -DHB_NO_SINGLE_HEADER_ERROR -DHAVE_GOBJECT -DHB_EXTERN= --cflags-end -I/private/tmp/harfbuzz-20230712-59949-4yuwuj/harfbuzz-7.1.0/src -I/private/tmp/harfbuzz-20230712-59949-4yuwuj/harfbuzz-7.1.0/build/src -I/private/tmp/harfbuzz-20230712-59949-4yuwuj/harfbuzz-7.1.0/. -I/private/tmp/harfbuzz-20230712-59949-4yuwuj/harfbuzz-7.1.0/build/. --filelist=/private/tmp/harfbuzz-20230712-59949-4yuwuj/harfbuzz-7.1.0/build/src/libharfbuzz-gobject.0.dylib.p/HarfBuzz_0.0_gir_filelist --include=GObject-2.0 --include=freetype2-2.0 --symbol-prefix=hb --symbol-prefix=hb_gobject --identifier-prefix=hb_ --pkg-export=harfbuzz-gobject --cflags-begin -DHAVE_CONFIG_H -I/private/tmp/harfbuzz-20230712-59949-4yuwuj/harfbuzz-7.1.0/. -I/private/tmp/harfbuzz-20230712-59949-4yuwuj/harfbuzz-7.1.0/build/. -I/usr/local/Cellar/pcre2/10.42/include -I/usr/local/Cellar/glib/2.76.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.76.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libffi/3.4.4/include -I/usr/local/Cellar/glib/2.76.0/include -I/private/tmp/harfbuzz-20230712-59949-4yuwuj/harfbuzz-7.1.0/src/. -I/private/tmp/harfbuzz-20230712-59949-4yuwuj/harfbuzz-7.1.0/build/src/. -I/usr/local/opt/libpng/include/libpng16 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/graphite2/1.3.14/include -I/usr/local/Cellar/gobject-introspection/1.76.0/include/gobject-introspection-1.0 --cflags-end --add-include-path=/usr/local/Cellar/gobject-introspection/1.76.0/share/gir-1.0 -L/private/tmp/harfbuzz-20230712-59949-4yuwuj/harfbuzz-7.1.0/build/src -L/usr/local/opt/freetype/lib -L/usr/local/Cellar/glib/2.76.0/lib -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/graphite2/1.3.14/lib --extra-library=harfbuzz -L/private/tmp/harfbuzz-20230712-59949-4yuwuj/harfbuzz-7.1.0/build/src --library harfbuzz-gobject -L/private/tmp/harfbuzz-20230712-59949-4yuwuj/harfbuzz-7.1.0/build/src -L/usr/local/Cellar/glib/2.76.0/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/freetype/lib -L/usr/local/Cellar/graphite2/1.3.14/lib -L/usr/local/Cellar/glib/2.76.0/lib -L/usr/local/opt/gettext/lib --extra-library=glib-2.0 --extra-library=intl --extra-library=gobject-2.0 --extra-library=m -L/usr/local/opt/freetype/lib --extra-library=freetype -L/usr/local/Cellar/graphite2/1.3.14/lib --extra-library=graphite2 -L/usr/local/Cellar/gobject-introspection/1.76.0/lib --extra-library=girepository-1.0 --sources-top-dirs /private/tmp/harfbuzz-20230712-59949-4yuwuj/harfbuzz-7.1.0/ --sources-top-dirs /private/tmp/harfbuzz-20230712-59949-4yuwuj/harfbuzz-7.1.0/build/
[102/108] clang++ -Isrc/libharfbuzz-subset.0.dylib.p -Isrc -I../src -I. -I.. -fcolor-diagnostics -Wall -Winvalid-pch -std=c++11 -fno-exceptions -fno-rtti -O3 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -DHAVE_CONFIG_H -Wno-non-virtual-dtor -MD -MQ src/libharfbuzz-subset.0.dylib.p/hb-subset-plan.cc.o -MF src/libharfbuzz-subset.0.dylib.p/hb-subset-plan.cc.o.d -o src/libharfbuzz-subset.0.dylib.p/hb-subset-plan.cc.o -c ../src/hb-subset-plan.cc
ninja: build stopped: subcommand failed.
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/ninja -C /private/tmp/harfbuzz-20230712-59949-4yuwuj/harfbuzz-7.1.0/build -v

Do not report this issue to Homebrew/brew or Homebrew/homebrew-core!

These open issues may also help:
harfbuzz 8.0.1 https://github.com/Homebrew/homebrew-core/pull/136401
```

**Comment by behdad** [comment] 2023-07-12 18:58
Duplicate of https://github.com/harfbuzz/harfbuzz/issues/4138

**Closed by behdad** 2023-07-12 18:58 UTC
