### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4726] opened 2024-05-24 15:31 UTC
I merged varc-table branch. Not sure what to call the new release. 9?

I wish I had implemented the updated beyond64k as well as other changed proposals (`GLYF` etc) as well, but that seems like a lot of work.

**Comment by khaledhosny** [comment] 2024-05-25 18:24
Can I drop autotools (and require C++14) now?

**Comment by behdad** [comment] 2024-05-25 18:26
Remind me again, how are we making releases?

**Comment by khaledhosny** [comment] 2024-05-25 18:31
https://github.com/harfbuzz/harfbuzz/blob/main/RELEASING.md

After that I create a new release on GitHub releases and copy the NEWS there, then CI will push the release tarball built with `make dist` to the releases page, as well as Windows binaries.

**Comment by alerque** [comment] 2024-05-25 18:34
What's the motivating factor trying to drop autotools? Last I looked the release process with it was almost completely automated including artifact posting to GitHub. Is there something that is making cutting releases with it difficult? I'm happy to help with it a bit as needed including fixing up any release tooling so the process is as painless as possible until such a time as #4720 is resolved.

(Along the lines of release automation but not at all the same problem, it is probably worth reviewing release security again because ① it would be good to get signed artifacts and ② GitHub's transparency issues with release artifacts are not getting fixed.)

**Comment by behdad** [comment] 2024-05-25 18:35
> Can I drop autotools (and require C++14) now?

How about we call autotools unmaintained as well and rely on community (eg. @alerque to maintain it?)

**Comment by behdad** [comment] 2024-05-25 18:36
I don't have a strong preference here. @khaledhosny you are the maintainer, so your call.

**Comment by behdad** [comment] 2024-05-25 18:36
We can also do a Twitter poll.

**Comment by alerque** [comment] 2024-05-25 18:38
Looking over the pre-release checklist, about half of that could be automated away. The changelog stuff *could* be too (e.g. with `git cliff` or similar), but I'm not even counting that. IF the NEWS and API changes are document by hand, basically everything else can be automated. There shouldn't be numbers to bump in multiple files, project wide search and replaces, etc.

**Comment by khaledhosny** [comment] 2024-05-25 18:55
I want to simplify build system maintenance and release process. Unlike CMake, autotools tarballs need to include generated files which we don’t keep in the repository, so it must be generated with `make dist` which means we must always keep it working. Often breakage is found only after release because `make dist` missed a file that meson needs, or some build step got updated in meson but not the automake files, etc. We can’t carry legacy baggage indefinitely.

We keep getting issues like these all the time, and since do don’t actively use autotools other than for creating tarballs, we often find about them after releases.

If I’m allowed to use `meson dist` (which will create tarballs without any of the generated autotools scripts), and stop running `make distcheck` on CI jobs, I’m fine with keeping autotools as community maintained.

**Comment by alerque** [comment] 2024-05-25 19:02
> Often breakage is found only after release because `make dist` missed a file that meson needs

The purpose of `make distcheck` is to confirm that everything needed to rebuild is included in `make dist`. That it isn't confirming at that point that meson can build is a shortcoming of CI for sure. Also one there are hooks to fix.

My concern with relegating one to "community maintained" is we'll end up with releases broken in one because they were only checked in one, and tagging yet another new release to fix a non-maintained build system is just going to be more friction not less. The most important time to confirm both fully work is right before a release, not after. If the release process can't be simplified without this so that both are confirmed working easily before the release is posted publicly then of course we should deal with that.

**Comment by behdad** [comment] 2024-05-25 19:04
We have a distcheck bot already. So I wonder if missing-files is a real concern for releases. I know it happens a lot in PRs, but that's fine to me to fix by the PR author.

**Comment by alerque** [comment] 2024-05-25 19:06
I'll have to check, but Khaled probably has a point there. We do have a distcheck and a meson build check, but we might be missing the daisy-chain scenario one where we have to make sure the Meson build works when being run from an autotools generated sources tarball, which won't have everything from the repository unless explicitly included. But yes is is something we *can* check for to eliminate last minute failure scenarios.

**Comment by debohman** [comment] 2024-05-26 22:33
Note that ICU-75 requires c++17.

**Comment by khaledhosny** [comment] 2024-06-27 15:45
https://github.com/harfbuzz/harfbuzz/releases/tag/9.0.0

**Closed by khaledhosny** 2024-06-27 15:45 UTC
