### ISSUE TITLE
AGA Aladdin Regular font not work

### ISSUE THREAD

**Issue by realfinder** [harfbuzz/harfbuzz#2975] opened 2021-05-08 00:25 UTC
Hi

I note that AGA Aladdin Regular will case libass to fallback to the default font or even worst it will show
![image](https://user-images.githubusercontent.com/2512153/117519573-c5a39580-afac-11eb-8b3a-5217e2adb38d.png)

the font just in case [AGA-Aladdin-Regular.zip](https://github.com/harfbuzz/harfbuzz/files/6444808/AGA-Aladdin-Regular.zip)
 
Thanks in advance.

**Comment by realfinder** [comment] 2021-05-08 00:37
maybe it same as https://github.com/libass/libass/issues/156 ? if it same problem I note Khaled Hosny mentioned a script https://github.com/libass/libass/issues/156#issuecomment-120733672 is it still working? is it used [here](https://web.archive.org/web/20200120235210/https://www.msoms-anime.net/showthread.php?t=190312)?

**Comment by khaledhosny** [comment] 2021-05-11 15:39
Duplicate of #681

**Closed by khaledhosny** 2021-05-11 15:39 UTC

**Comment by khaledhosny** [comment] 2021-05-11 15:42
I don’t know if I still have that script, but I haven’t used it in a long time. These fonts don’t work anywhere except Windows and should better be avoided.
