### ISSUE TITLE
NULL pointer deref in hb_ot_layout_get_baseline_with_fallback

### ISSUE THREAD

**Issue by lattera** [harfbuzz/harfbuzz#3534] opened 2022-04-15 22:06 UTC
I've found that in some cases, pango may call `hb_ot_layout_get_baseline_with_fallback` with the `font` parameter being NULL. This causes a NULL pointer deref in `hb_ot_layout_get_baseline`. I'm not 100% sure what those cases are due to the difficulty in reproducing the issue.

The backstory:

HardenedBSD's recent package builds have occasionally experienced issues when building doxygen. `/usr/local/bin/dot` would crash with signal 11. Some builds would succeed, others would fail even though no changes were made to doxygen, pango, or any other related dependency.

When diving deeper, I found that an attempt to access a NULL pointer was made right at the beginning of the referenced function. I'm thinking that the call to `hb_ot_layout_get_baseline_with_fallback` gets inlined in `hb_ot_layout_get_baseline_with_fallback`.

The attached patch is likely wrong (at the very least, it doesn't conform to the code style of the project), but at least provides a hint as to a possible workaround.

[harfbuzz.patch.txt](https://github.com/harfbuzz/harfbuzz/files/8497863/harfbuzz.patch.txt)

**Comment by khaledhosny** [comment] 2022-04-15 22:21
Duplicate of #3519

**Closed by khaledhosny** 2022-04-15 22:21 UTC

**Comment by behdad** [comment] 2022-04-18 17:51
That's fixed in Pango 1.50.7.
