### ISSUE TITLE
[hb-view] [utils] application of language

### ISSUE THREAD

**Issue by ctrlcctrlv** [harfbuzz/harfbuzz#2844] opened 2021-02-05 10:52 UTC
Greetings.

For the purposes of proofing and debugging complex OpenType fonts, `hb-view` is an excellent tool for the font developer that only uses free software.

However, the necessity of converting language tags easily leads to confusion and bugs. I discovered such today while generating https://kittens.ph/syriac/index.html to show a friend working on a Unicode proposal. 

The language as it exists in the font, SYRN, must be specified syc-Syrn, as in HTML. This makes proofing more difficult when I'd like to stick "close to OpenType". It also complicates the use of language tags which are not yet in the standard, which is something that we need to do not infrequently when working on Unicode.

Can it please be considered to allow us to pass OpenType native script/language pairs to the HarfBuzz debugging/proofing utilities?

**Comment by behdad** [comment] 2021-02-06 22:19
Try `--language=-hbotSYRN`.

**Comment by behdad** [comment] 2021-02-06 22:23
I thought we recently documented this. But can't find.

**Comment by behdad** [comment] 2021-02-06 22:24
See also https://github.com/harfbuzz/harfbuzz/pull/645

**Comment by ctrlcctrlv** [comment] 2021-02-07 22:39
Thank you! I will open a PR against the docs to close this issue.

**Comment by khaledhosny** [comment] 2021-02-07 23:12
Duplicate of #2680

**Closed by khaledhosny** 2021-02-07 23:12 UTC
